'use client';

import React, { createContext, useContext, useState, useEffect, useMemo, useCallback } from 'react';

// 한국어 / 영어 / 일본어 / 중국어 / 러시아어
type Language = 'ko' | 'en' | 'ja' | 'zh' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  // Helper for translating dynamic content (user-generated names, etc.)
  translateIfExists: (key: string, fallback: string) => string;
}

const translations = {
  ko: {
    'theme.light': '밝게',
    'theme.dark': '어둡게',
    'theme.toggle': '테마 변경',
    'language.toggle': '언어 변경',
    'nav.features': '기능',
    'nav.pricing': '가격',
    'nav.docs': '문서',
    'nav.signin': '로그인',
    'nav.getstarted': '시작하기',
    'hero.title': '하나로 통합된',
    'hero.subtitle': 'API를 경험해보세요',
    'hero.description': '여러 공공 API를 단일 통합 인터페이스를 통해 연결하여 개발을 간소화하세요. 더 빠르게 구축하고, 더 쉽게 통합하세요.',
    'hero.cta': '시작하기',
    'hero.learn': '더 알아보기',
    'features.title': '기능',
    'features.description': 'API를 효율적으로 연결하고 관리하는 데 필요한 모든 것.',
    'feature.integration.title': 'API 통합',
    'feature.integration.description': '여러 공공 API를 하나의 인터페이스로 통합합니다.',
    'feature.performance.title': '빠른 처리',
    'feature.performance.description': '최적화된 성능으로 빠른 데이터 처리를 제공합니다.',
    'feature.security.title': '안전한 연결',
    'feature.security.description': '보안이 강화된 안전한 API 연결을 보장합니다.',
    'footer.built': 'API Bridge 팀에서 제작. 소스 코드는',
    'footer.github': 'GitHub',
    'footer.available': '에서 확인할 수 있습니다.',
    'brand': 'API 브릿지',
    // Dashboard navigation
    'nav.dashboard': '대시보드',
    'nav.apiBoard': 'API 게시판',
    'nav.suggestions': '커스텀API 생성',
    'nav.monitoring': '모니터링',
    'nav.settings': '설정',
    'nav.admin': '관리자',
    'nav.menu.toggle': '탐색 메뉴 전환',
    // Dashboard stats
    'dashboard.stats.totalApis': '총 API',
    'dashboard.stats.activeKeys': '활성 키',
    'dashboard.stats.totalCalls': '총 호출 (30일)',
    'dashboard.stats.uptime': '가동 시간',
    'dashboard.stats.lastMonth': '지난달 이후',
    'dashboard.stats.lastWeek': '지난주 이후',
    'dashboard.stats.vsLastMonth': '지난달 대비',
    'dashboard.stats.allActiveApis': '모든 활성 API에서',
    // Dashboard API table
    'dashboard.myApis': '내 API',
    'dashboard.myApis.description': '사용자 지정 데이터 소스 API를 관리합니다.',
    'dashboard.createApi': 'API 생성',
    'dashboard.table.apiName': 'API 이름',
    'dashboard.table.status': '상태',
    'dashboard.table.calls': '호출 (30일)',
    'dashboard.table.successRate': '성공률',
    'dashboard.table.sharing': '공유',
    'dashboard.table.actions': '작업',
    'dashboard.badge.imported': '가져온 API',
    'dashboard.badge.myApi': '내 API',
    'dashboard.originalAuthor': '원작자',
    'dashboard.status.active': '활성',
    'dashboard.status.inactive': '비활성',
    'dashboard.status.error': '오류',
    'dashboard.share.sharing': '공유중',
    'dashboard.share.share': '공유',
    'dashboard.share.imported': '공유된 API',
    // Dashboard additional
    'dashboard.loading': '로딩 중...',
    'dashboard.noCreatedApis': '생성된 API가 없습니다.',
    'dashboard.noSearchResults': '검색 결과가 없습니다.',
    'dashboard.noImportedApis': '가져온 API가 없습니다.',
    'dashboard.myApisButton': '내API',
    'dashboard.importedApisButton': '가져온API',
    'dashboard.searchPlaceholder': 'API 이름을 검색하세요',
    'dashboard.table.method': '메서드',
    'dashboard.table.parameters': '파라미터',
    'dashboard.parametersCount': '개',
    'dashboard.noDescription': '설명이 없습니다',
    'dashboard.delete.title': 'API를 삭제하시겠습니까?',
    'dashboard.delete.warning': '이 작업은 되돌릴 수 없습니다.',
    'dashboard.delete.cancel': '아니오',
    'dashboard.delete.confirm': '예',
    // API Detail Modal
    'dashboard.modal.basicInfo': '기본 정보',
    'dashboard.modal.apiPath': 'API 경로',
    'dashboard.modal.status': '상태',
    'dashboard.modal.totalCalls': '총 호출 수',
    'dashboard.modal.successRate': '성공률',
    'dashboard.modal.parameters': '파라미터',
    'dashboard.modal.noParameters': '파라미터가 없습니다.',
    'dashboard.modal.required': '필수',
    'dashboard.modal.originalAuthor': '원작자 정보',
    'dashboard.modal.sharedBy': '이 API는',
    'dashboard.menu.toggle': '메뉴 전환',
    'dashboard.menu.actions': '작업',
    'dashboard.menu.viewAnalytics': '분석 보기',
    'dashboard.menu.keyManagement': '키 관리',
    'dashboard.menu.settings': '설정',
    'dashboard.menu.apiKey': 'API 키',
    // User menu
    'user.menu.myAccount': '내 계정',
    'user.menu.settings': '설정',
    'user.menu.support': '지원',
    'user.menu.logout': '로그아웃',
    'user.menu.toggle': '사용자 메뉴 전환',
    // Sample API data (for demo)
    'api.weatherData': '날씨 데이터 API',
    'api.stockMarket': '주식 시장 피드',
    'api.locationService': '사용자 위치정보 서비스',
    'api.productCatalog': '제품 카탈로그 API',
    'api.paymentGateway': '결제 게이트웨이 브릿지',
    // Pricing page
    'pricing.title': '최소한의 비용으로 최대한의 효과',
    'pricing.subtitle': '귀하의 필요에 맞는 플랜을 선택하고 지금 바로 구축을 시작하세요.',
    'pricing.free.title': 'Free',
    'pricing.free.description': '개인 프로젝트 및 학습용으로 시작하기에 좋습니다.',
    'pricing.free.cta': '무료로 시작하기',
    'pricing.pro.title': 'Pro',
    'pricing.pro.description': '강력한 기능이 필요한 전문가 및 팀을 위한 플랜입니다.',
    'pricing.pro.cta': 'Pro 플랜 시작하기',
    'pricing.pro.popular': '가장 인기있는',
    'pricing.pro.price': '₩22,000',
    'pricing.pro.period': '/월',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API 생성',
    'pricing.feature.apiCalls.free': '월 10,000건의 API 호출',
    'pricing.feature.support.free': '커뮤니티 지원',
    'pricing.feature.apiCreation.pro': '무제한 API 생성',
    'pricing.feature.apiCalls.pro': '월 1,000,000건의 API 호출',
    'pricing.feature.ai': 'AI+ 기능',
    'pricing.feature.support.pro': '우선 이메일 지원',
    'pricing.feature.analytics': '고급 분석 기능',
    'pricing.footer': '© 2024 API 브릿지. 모든 권리 보유.',
    // Login page
    'login.title': 'API 브릿지',
    'login.description': '계정에 로그인하려면 아래에 이메일을 입력하세요',
    'login.email': '이메일',
    'login.password': '비밀번호',
    'login.forgotPassword': '비밀번호를 잊으셨나요?',
    'login.signIn': '로그인',
    'login.signInGoogle': 'Google로 로그인',
    'login.noAccount': '계정이 없으신가요?',
    'login.signUp': '가입하기',
    'login.emailPlaceholder': 'm@example.com',
    // API Board page
    'apiBoard.myShared': '내가 공유한 키',
    'apiBoard.imported': '가져온 키',
    'apiBoard.totalBoard': '총 게시판 키',
    'apiBoard.thisMonth': '이번 달',
    'apiBoard.thisWeek': '이번 주',
    'apiBoard.sharedApis': '공유된 API',
    'apiBoard.description': '커뮤니티에서 공유한 커스텀 API를 탐색하고 사용해보세요.',
    'apiBoard.searchPlaceholder': 'API 이름, 설명 또는 작성자로 검색...',
    'apiBoard.table.apiName': 'API 이름',
    'apiBoard.table.author': '작성자',
    'apiBoard.table.description': '설명',
    'apiBoard.table.usageCount': '사용 수',
    'apiBoard.table.sharedDate': '공유일',
    'apiBoard.table.actions': '작업',
    'apiBoard.useButton': '사용하기',
    'apiBoard.noResults': '검색 결과가 없습니다',
    'apiBoard.noResultsDesc': '다른 검색어로 시도해보세요',
    'apiBoard.title': '공유된 API',
    'apiBoard.stats.sharedApis': '공유된 API',
    'apiBoard.stats.sharedApisDesc': '다른 사용자가 공유한 API',
    'apiBoard.stats.activeUsers': '활성 사용자',
    'apiBoard.stats.activeUsersDesc': 'API를 공유한 사용자 수',
    'apiBoard.stats.totalDownloads': '총 다운로드',
    'apiBoard.stats.totalDownloadsDesc': '이번 달 API 사용 횟수',
    'apiBoard.importConfirmTitle': 'API 가져오기 확인',
    'apiBoard.importConfirmMessage': '를 내 대시보드로 가져오시겠습니까?',
    'apiBoard.importConfirmDescription': '가져온 후에는 내 API 목록에서 확인할 수 있습니다.',
    'apiBoard.importConfirmYes': '예',
    'apiBoard.importConfirmCancel': '취소',
    // Custom API Creation page
    'suggestions.title': '커스텀API 생성',
    'suggestions.description': '필요한 데이터를 설명하면 AI가 커스텀 API 생성을 도와드립니다.',
    // Monitoring page
    'monitoring.systemStatus': '시스템 상태',
    'monitoring.statusHealthy': '정상 작동',
    'monitoring.lastCheck': '마지막 확인',
    'monitoring.apiSources': 'API 소스',
    'monitoring.connectedHealthy': '연결되었고 건강함',
    'monitoring.activeUsers': '활성 사용자',
    'monitoring.onlineLast15': '지난 15분 동안 온라인',
    'monitoring.securityAlerts': '보안 경고',
    'monitoring.noCriticalAlerts': '오늘 중요한 경고 없음',
    'monitoring.grafanaDashboard': 'Grafana 대시보드',
    'monitoring.grafanaDescription': '실시간 시스템 메트릭 및 성능.',
    'monitoring.grafanaEmbed': 'Grafana 대시보드가 여기에 포함됩니다',
    'monitoring.kibanaDashboard': 'Kibana 대시보드',
    'monitoring.kibanaDescription': '로그 분석 및 애플리케이션 추적.',
    'monitoring.kibanaEmbed': 'Kibana 대시보드가 여기에 포함됩니다',
    'monitoring.userActivity': '사용자 활동 스트림',
    'monitoring.userActivityDescription': '플랫폼 전반의 최근 사용자 활동 개요.',
    'monitoring.table.user': '사용자',
    'monitoring.table.action': '작업',
    'monitoring.table.timestamp': '타임스탬프',
    'monitoring.table.ipAddress': 'IP 주소',
    // Settings page
    'settings.profile': '프로필',
    'settings.profileDescription': '개인 정보를 관리합니다.',
    'settings.name': '이름',
    'settings.email': '이메일',
    'settings.save': '저장',
    'settings.security': '보안',
    'settings.securityDescription': '비밀번호 및 2단계 인증을 관리합니다.',
    'settings.enable2fa': '2단계 인증 활성화',
    'settings.currentPassword': '현재 비밀번호',
    'settings.newPassword': '새 비밀번호',
    'settings.updatePassword': '비밀번호 업데이트',
    'settings.notifications': '알림',
    'settings.notificationsDescription': '알림 기본 설정을 관리합니다.',
    'settings.securityEmails': '보안 이메일',
    'settings.apiAlerts': 'API 사용량 알림',
    // AI Key settings
    'settings.aiKey.title': '개인 AI 키 등록',
    'settings.aiKey.description': '개인 AI API 키를 등록하여 서비스를 이용하세요',
    'settings.aiKey.loading': '로딩 중...',
    'settings.aiKey.noKeys': '등록된 키가 없습니다',
    'settings.aiKey.form.keyName': '키 이름',
    'settings.aiKey.form.keyNamePlaceholder': '예: gemini, openai, claude',
    'settings.aiKey.form.keyNameHelp': 'AI 서비스 이름을 입력하세요 (예: gemini, openai, claude)',
    'settings.aiKey.form.apiKey': 'API 키',
    'settings.aiKey.form.apiKeyPlaceholder': 'AI API 키를 입력하세요',
    'settings.aiKey.form.apiKeyHelp': '보안을 위해 키는 암호화되어 저장됩니다',
    'settings.aiKey.form.description': '키 설명 (선택사항)',
    'settings.aiKey.form.descriptionPlaceholder': '이 API 키에 대한 설명을 입력하세요',
    'settings.aiKey.form.registering': '등록 중...',
    'settings.aiKey.form.registerButton': '키 등록',
    'settings.aiKey.validation.keyNameRequired': '키 이름을 입력하세요',
    'settings.aiKey.validation.apiKeyRequired': 'API 키를 입력하세요',
    'settings.aiKey.validation.keyNameExists': '이미 등록된 키 이름입니다',
    'settings.newsletter': '뉴스레터 및 업데이트',
    'settings.savePreferences': '기본 설정 저장',
    // Admin page
    'admin.accessDenied': '접근 권한이 없습니다.',
    'admin.adminOnly': '관리자만 접근할 수 있는 페이지입니다.',
    'admin.totalUsers': '총 사용자',
    'admin.totalApis': '총 API',
    'admin.totalCalls': '총 호출 수',
    'admin.activeUsers': '활성 사용자',
    'admin.lastMonth': '지난 달 대비',
    'admin.lastWeek': '지난 주 대비',
    'admin.vsLastMonth': '지난 달 대비',
    'admin.allUsers': '전체 사용자 중',
    'admin.userManagement': '사용자 관리',
    'admin.userManagementDescription': '시스템에 등록된 모든 사용자를 관리할 수 있습니다.',
    'admin.systemSettings': '시스템 설정',
    'admin.table.userName': '사용자 이름',
    'admin.table.email': '이메일',
    'admin.table.role': '권한',
    'admin.table.status': '상태',
    'admin.table.joinDate': '가입일',
    'admin.role.admin': '관리자',
    'admin.role.user': '일반 사용자',
    'admin.status.active': '활성',
    'admin.status.inactive': '비활성',
    'admin.editButton': '편집',
    // Admin External API Management
    'admin.externalApi.title': '외부 API 관리',
    'admin.externalApi.description': '커스텀 API 생성을 위한 외부 API를 등록하고 관리합니다',
    'admin.externalApi.form.title': '새 API 등록',
    'admin.externalApi.form.name': 'API 이름',
    'admin.externalApi.form.namePlaceholder': '예: 주택통계',
    'admin.externalApi.form.description': 'API 설명',
    'admin.externalApi.form.descriptionPlaceholder': '예: (인구주택총조사) 주택 통계 제공 API',
    'admin.externalApi.form.issuer': 'API 발급기관',
    'admin.externalApi.form.issuerPlaceholder': '예: SGIS',
    'admin.externalApi.form.credentialId': 'Credential ID',
    'admin.externalApi.form.credentialIdPlaceholder': '예: SGIS',
    'admin.externalApi.form.url': 'API URL',
    'admin.externalApi.form.urlPlaceholder': 'https://sgisapi.kostat.go.kr/OpenAPI3/stats/house.json',
    'admin.externalApi.form.httpMethod': 'HTTP 메소드',
    'admin.externalApi.form.registering': '등록 중...',
    'admin.externalApi.form.registerButton': 'API 등록',
    'admin.externalApi.parameters.title': '파라미터',
    'admin.externalApi.parameters.count': '개',
    'admin.externalApi.parameters.add': '파라미터 추가',
    'admin.externalApi.parameters.required': '필수',
    'admin.externalApi.parameters.form.name': '파라미터 이름',
    'admin.externalApi.parameters.form.namePlaceholder': '예: accessToken',
    'admin.externalApi.parameters.form.type': '타입',
    'admin.externalApi.parameters.form.description': '설명',
    'admin.externalApi.parameters.form.descriptionPlaceholder': '예: 액세스키',
    'admin.externalApi.parameters.form.defaultValue': '기본값 (선택)',
    'admin.externalApi.parameters.form.defaultValuePlaceholder': '기본값 입력',
    'admin.externalApi.parameters.form.requiredParam': '필수 파라미터',
    'admin.externalApi.parameters.form.addButton': '추가',
    'admin.externalApi.parameters.form.cancelButton': '취소',
    'admin.externalApi.list.title': '등록된 외부 API',
    'admin.externalApi.list.count': '개',
    'admin.externalApi.list.empty': '등록된 외부 API가 없습니다',
    'admin.externalApi.list.active': '활성',
    'admin.externalApi.list.inactive': '비활성',
    'admin.externalApi.list.registeredDate': '등록일',
    'admin.externalApi.validation.nameRequired': 'API 이름을 입력하세요',
    'admin.externalApi.validation.urlRequired': 'API URL을 입력하세요',
    'admin.externalApi.validation.urlInvalid': '올바른 URL 형식이 아닙니다',
    'admin.externalApi.validation.issuerRequired': 'API 발급기관을 입력하세요',
    'admin.externalApi.validation.credentialRequired': 'Credential ID를 입력하세요',
    'admin.externalApi.validation.nameExists': '이미 등록된 API 이름입니다',
    'admin.externalApi.success.registered': '외부 API가 성공적으로 등록되었습니다',
    'admin.externalApi.success.registeredAlert': '외부 API가 성공적으로 등록되었습니다!',
    'admin.externalApi.success.deleted': '외부 API가 성공적으로 삭제되었습니다',
    'admin.externalApi.success.deletedAlert': '외부 API가 성공적으로 삭제되었습니다!',
    'admin.externalApi.error.registrationFailed': '외부 API 등록 실패:',
    'admin.externalApi.error.registrationAlert': '외부 API 등록에 실패했습니다. 다시 시도해주세요.',
    'admin.externalApi.error.deletionFailed': '외부 API 삭제 실패:',
    'admin.externalApi.error.deletionAlert': '외부 API 삭제에 실패했습니다. 다시 시도해주세요.',
    'admin.externalApi.confirm.delete': '이 API를 삭제하시겠습니까?',
    // Time units and actions (for monitoring page)
    'time.minutesAgo': '분 전',
    'time.hoursAgo': '시간 전',
    'time.daysAgo': '일 전',
    'time.weeksAgo': '주 전',
    'action.createProduct': '"제품 피드" API 생성',
    'action.createKey': '"날씨 API"에 대한 새 키 생성',
    'action.deleteApi': '"오래된 사용자 서비스" API 삭제',
    'action.updateSettings': '"제품 피드" 설정 업데이트',
    'action.userLogin': '사용자 로그인',
    // Custom API creation form
    'suggestions.dataDescription': '데이터 설명',
    'suggestions.examplePlaceholder': '예: "전 세계 대학의 순위, 학비, 위치 데이터"',
    'suggestions.createButton': '생성하기',
    'suggestions.helpText': '찾고 있는 데이터에 대한 명확하고 간결한 설명을 제공하십시오.',
    'suggestions.recommendedTitle': '추천 API',
    'suggestions.recommendedDescription': '귀하의 요구에 맞는 몸 가지 API는 다음과 같습니다.',
    'suggestions.noResultsTitle': '결과를 찾을 수 없음',
    'suggestions.noResultsDescription': 'AI가 귀하의 쿼리에 대한 API를 찾을 수 없습니다. 설명을 바꾸어 다시 시도해 보세요.',
    'suggestions.errorTitle': '오류가 발생했습니다.',
    'suggestions.errorDescription': 'API를 생성하는데 실패했습니다. 나중에 다시 시도해 주세요.',
    // API Usage page
    'apiUsage.title': 'API 사용',
    'apiUsage.description': '생성한 커스텀 API를 실행하고 테스트해보세요',
    'apiUsage.myCustomApis': '내 커스텀 API',
    'apiUsage.selectApiDescription': '실행할 API를 선택하세요',
    'apiUsage.loading': '로딩 중...',
    'apiUsage.noApis': '생성된 API가 없습니다.',
    'apiUsage.createApiButton': 'API 생성하기',
    'apiUsage.parametersCount': '개 파라미터',
    'apiUsage.execution.title': 'API 실행',
    'apiUsage.execution.description': '파라미터를 설정하고 API를 실행하세요',
    'apiUsage.execution.selectApiPrompt': '실행할 API를 선택해주세요',
    'apiUsage.execution.executing': '실행 중...',
    'apiUsage.execution.executeButton': 'API 실행',
    'apiUsage.parameters.title': '파라미터',
    'apiUsage.parameters.inputPlaceholder': '값을 입력하세요',
    'apiUsage.results.title': '실행 결과',
    'apiUsage.results.copyButton': '복사',
    'apiUsage.results.hideButton': '숨기기',
    'apiUsage.results.description': 'API 실행 결과가 아래에 표시됩니다',
    'apiUsage.results.copied': '클립보드에 복사되었습니다!',
    // API Board sample data
    'api.movieRecommendation': '영화 추천 API',
    'api.movieRecommendationDesc': '개인 취향 기반 영화 추천 시스템',
    'api.cryptoPriceTracker': '암호화폐 가격 트래커',
    'api.cryptoPriceTrackerDesc': '실시간 암호화폐 가격 추적 API',
    'api.socialMediaAnalyzer': '소셜 미디어 분석기',
    'api.socialMediaAnalyzerDesc': 'SNS 게시물 감정 분석 및 트렌드 파악',
    'api.deliveryOptimizer': '음식 배달 최적화',
    'api.deliveryOptimizerDesc': '배달 경로 최적화 및 시간 예측',
    // API Categories
    'apiCatalog.title': '정부 API 카탈로그',
    'apiCatalog.subtitle': '대한민국 정부기관에서 제공하는 다양한 공공데이터 API를 한곳에서',
    'apiCatalog.cta': '모든 API 둘러보기',
    'category.culture': '문화·관광',
    'category.disaster': '재난·안전',
    'category.agriculture': '농업·축산',
    'category.realestate': '부동산·건설',
    'category.economy': '경제·금융',
    'category.employment': '고용·취업',
    'category.environment': '환경·기상',
    'category.transport': '교통·지역',
    'category.legal': '법령·특허',
    'category.education': '교육·의료',
    'category.nature': '자연·레저',
    'api.performance': '공연전시정보',
    'api.performance.data': '공연, 전시, 문화시설 정보',
    'api.tourism': '관광정보',
    'api.tourism.data': '국내 관광지, 숙박, 음식점, 축제, 여행코스',
    'api.wildfire': '산불발생이력',
    'api.wildfire.data': '산불 발생 및 진화 현황',
    'api.fire': '화재발생정보',
    'api.fire.data': '화재발생 통계, 소방서 정보',
    'api.livestock': '축산물이력정보',
    'api.livestock.data': '축산물 이력, 농산물 안전정보',
    'api.fishery': '수산물가격정보',
    'api.fishery.data': '수산물 가격, 어획량 정보',
    'api.townhouse': '연립다세대 실거래가',
    'api.townhouse.data': '연립다세대 실거래 정보 (계약 금액, 면적, 층수 등)',
    'api.apartment': '아파트 매매 실거래가',
    'api.apartment.data': '아파트 실거래 정보',
    'api.vehicle': '자동차등록정보',
    'api.vehicle.data': '자동차 등록번호 기반의 차량 종합 정보',
    'api.business': '사업자등록상태',
    'api.business.data': '사업자등록상태, 휴폐업정보',
    'api.ecos': '한국은행 ECOS',
    'api.ecos.data': '경제통계, 환율, 금리',
    'api.dart': 'DART 공시정보',
    'api.dart.data': '상장기업의 공시 정보, 재무제표, 사업보고서',
    'api.trade': '수출입통계',
    'api.trade.data': '수출입 통계, 관세 정보',
    'api.trader': '거래업체정보',
    'api.trader.data': '무역 거래업체 연도별 거래 통계 정보',
    'api.worknet': '워크넷 채용정보',
    'api.worknet.data': '구인구직 정보',
    'api.publicjob': '공공취업정보',
    'api.publicjob.data': '공공기관 채용정보',
    'api.venture': '중소벤처24',
    'api.venture.data': '중소벤처기업 지원사업 공고',
    'api.airpollution': '대기오염정보',
    'api.airpollution.data': '미세먼지, 대기질 정보',
    'api.weather': '날씨정보',
    'api.weather.data': '초단기실황, 단기예보',
    'api.earthquake': '지진정보',
    'api.earthquake.data': '지진발생 정보, 지진해일 정보',
    'api.subway': '지하철 실시간 도착정보',
    'api.subway.data': '지하철 실시간 도착 정보',
    'api.sgis': 'SGIS 통계정보',
    'api.sgis.data': '지도 기반 인구통계 정보, 지역 통계 등',
    'api.law': '국가법령정보',
    'api.law.data': '법령 정보, 판례 정보',
    'api.patent': '특허정보',
    'api.patent.data': '특허, 실용신안, 디자인, 상표 정보',
    'api.neis': '나이스(NEIS)',
    'api.neis.data': '학교 정보, 급식 정보',
    'api.hospital': '병원정보',
    'api.hospital.data': '병원 및 의료기관 기본정보',
    'api.medicine': '의약품정보',
    'api.medicine.data': '의약품 정보, 식품 안전정보',
    'api.mountain': '등산로정보',
    'api.mountain.data': '등산로 정보, 휴양림 정보',
    'api.safety': '해외안전정보',
    'api.safety.data': '여행경보, 국가별 안전정보',
  },
  en: {
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.toggle': 'Toggle theme',
    'language.toggle': 'Toggle language',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.docs': 'Docs',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'hero.title': 'Experience Unified',
    'hero.subtitle': 'API Integration',
    'hero.description': 'Simplify your development by connecting multiple public APIs through a single, unified interface. Build faster, integrate easier.',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    'features.title': 'Features',
    'features.description': 'Everything you need to connect and manage your APIs efficiently.',
    'feature.integration.title': 'API Integration',
    'feature.integration.description': 'Integrate multiple public APIs through a single interface.',
    'feature.performance.title': 'Fast Processing',
    'feature.performance.description': 'Provides fast data processing with optimized performance.',
    'feature.security.title': 'Secure Connection',
    'feature.security.description': 'Ensures secure API connections with enhanced security.',
    'footer.built': 'Built by API Bridge team. The source code is available on',
    'footer.github': 'GitHub',
    'footer.available': '.',
    'brand': 'API Bridge',
    // Dashboard navigation
    'nav.dashboard': 'Dashboard',
    'nav.apiBoard': 'API Board',
    'nav.suggestions': 'Custom API Creation',
    'nav.monitoring': 'Monitoring',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.menu.toggle': 'Toggle navigation menu',
    // Dashboard stats
    'dashboard.stats.totalApis': 'Total APIs',
    'dashboard.stats.activeKeys': 'Active Keys',
    'dashboard.stats.totalCalls': 'Total Calls (30d)',
    'dashboard.stats.uptime': 'Uptime',
    'dashboard.stats.lastMonth': 'since last month',
    'dashboard.stats.lastWeek': 'since last week',
    'dashboard.stats.vsLastMonth': 'from last month',
    'dashboard.stats.allActiveApis': 'across all active APIs',
    // Dashboard API table
    'dashboard.myApis': 'My APIs',
    'dashboard.myApis.description': 'Manage your custom data source APIs.',
    'dashboard.createApi': 'Create API',
    'dashboard.table.apiName': 'API Name',
    'dashboard.table.status': 'Status',
    'dashboard.table.calls': 'Calls (30d)',
    'dashboard.table.successRate': 'Success Rate',
    'dashboard.table.sharing': 'Sharing',
    'dashboard.table.actions': 'Actions',
    'dashboard.badge.imported': 'Imported API',
    'dashboard.badge.myApi': 'My API',
    'dashboard.originalAuthor': 'Original Author',
    'dashboard.status.active': 'Active',
    'dashboard.status.inactive': 'Inactive',
    'dashboard.status.error': 'Error',
    'dashboard.share.sharing': 'Sharing',
    'dashboard.share.share': 'Share',
    'dashboard.share.imported': 'Imported',
    // API Detail Modal
    'dashboard.modal.basicInfo': 'Basic Information',
    'dashboard.modal.apiPath': 'API Path',
    'dashboard.modal.status': 'Status',
    'dashboard.modal.totalCalls': 'Total Calls',
    'dashboard.modal.successRate': 'Success Rate',
    'dashboard.modal.parameters': 'Parameters',
    'dashboard.modal.noParameters': 'No parameters available.',
    'dashboard.modal.required': 'Required',
    'dashboard.modal.originalAuthor': 'Original Author',
    'dashboard.modal.sharedBy': 'This API is shared by',
    'dashboard.menu.toggle': 'Toggle menu',
    'dashboard.menu.actions': 'Actions',
    'dashboard.menu.viewAnalytics': 'View Analytics',
    'dashboard.menu.keyManagement': 'Key Management',
    'dashboard.menu.settings': 'Settings',
    'dashboard.menu.apiKey': 'API Key',
    // User menu
    'user.menu.myAccount': 'My Account',
    'user.menu.settings': 'Settings',
    'user.menu.support': 'Support',
    'user.menu.logout': 'Logout',
    'user.menu.toggle': 'Toggle user menu',
    // Sample API data (for demo)
    'api.weatherData': 'Weather Data API',
    'api.stockMarket': 'Stock Market Feed',
    'api.locationService': 'User Location Service',
    'api.productCatalog': 'Product Catalog API',
    'api.paymentGateway': 'Payment Gateway Bridge',
    // Pricing page
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs and start building right away.',
    'pricing.free.title': 'Free',
    'pricing.free.description': 'Perfect for getting started with personal projects and learning.',
    'pricing.free.cta': 'Get Started Free',
    'pricing.pro.title': 'Pro',
    'pricing.pro.description': 'For professionals and teams who need powerful features.',
    'pricing.pro.cta': 'Start Pro Plan',
    'pricing.pro.popular': 'Most Popular',
    'pricing.pro.price': '$22.00',
    'pricing.pro.period': '/month',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API creation',
    'pricing.feature.apiCalls.free': '10,000 API calls per month',
    'pricing.feature.support.free': 'Community support',
    'pricing.feature.apiCreation.pro': 'Unlimited API creation',
    'pricing.feature.apiCalls.pro': '1,000,000 API calls per month',
    'pricing.feature.ai': 'AI+ features',
    'pricing.feature.support.pro': 'Priority email support',
    'pricing.feature.analytics': 'Advanced analytics',
    'pricing.footer': '© 2024 API Bridge. All rights reserved.',
    // Login page
    'login.title': 'API Bridge',
    'login.description': 'Enter your email below to sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.signIn': 'Sign In',
    'login.signInGoogle': 'Sign in with Google',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.emailPlaceholder': 'm@example.com',
    // API Board page
    'apiBoard.myShared': 'My Shared Keys',
    'apiBoard.imported': 'Imported Keys',
    'apiBoard.totalBoard': 'Total Board Keys',
    'apiBoard.thisMonth': 'this month',
    'apiBoard.thisWeek': 'this week',
    'apiBoard.sharedApis': 'Shared APIs',
    'apiBoard.description': 'Explore and use custom APIs shared by the community.',
    'apiBoard.searchPlaceholder': 'Search by API name, description, or author...',
    'apiBoard.table.apiName': 'API Name',
    'apiBoard.table.author': 'Author',
    'apiBoard.table.description': 'Description',
    'apiBoard.table.usageCount': 'Usage Count',
    'apiBoard.table.sharedDate': 'Shared Date',
    'apiBoard.importButton': 'Import',
    'apiBoard.noResults': 'No search results',
    'apiBoard.noResultsDescription': 'Try a different search term.',
    'apiBoard.importConfirmTitle': 'Confirm API Import',
    'apiBoard.importConfirmMessage': 'Do you want to import {apiName} to your dashboard?',
    'apiBoard.importConfirmDescription': 'After importing, you can find it in your API list.',
    'apiBoard.importConfirmYes': 'Yes',
    'apiBoard.importConfirmCancel': 'Cancel',
    // Custom API Creation page
    'suggestions.title': 'Custom API Creation',
    'suggestions.description': 'Describe the data you need and AI will help create a custom API.',
    // Monitoring page
    'monitoring.systemStatus': 'System Status',
    'monitoring.statusHealthy': 'Healthy',
    'monitoring.lastCheck': 'last check',
    'monitoring.apiSources': 'API Sources',
    'monitoring.connectedHealthy': 'connected and healthy',
    'monitoring.activeUsers': 'Active Users',
    'monitoring.onlineLast15': 'online in last 15 minutes',
    'monitoring.securityAlerts': 'Security Alerts',
    'monitoring.noCriticalAlerts': 'no critical alerts today',
    'monitoring.grafanaDashboard': 'Grafana Dashboard',
    'monitoring.grafanaDescription': 'Real-time system metrics and performance.',
    'monitoring.grafanaEmbed': 'Grafana dashboard will be embedded here',
    'monitoring.kibanaDashboard': 'Kibana Dashboard',
    'monitoring.kibanaDescription': 'Log analysis and application tracing.',
    'monitoring.kibanaEmbed': 'Kibana dashboard will be embedded here',
    'monitoring.userActivity': 'User Activity Stream',
    'monitoring.userActivityDescription': 'Overview of recent user activity across the platform.',
    'monitoring.table.user': 'User',
    'monitoring.table.action': 'Action',
    'monitoring.table.timestamp': 'Timestamp',
    'monitoring.table.ipAddress': 'IP Address',
    // Settings page
    'settings.profile': 'Profile',
    'settings.profileDescription': 'Manage your personal information.',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.save': 'Save',
    'settings.security': 'Security',
    'settings.securityDescription': 'Manage your password and two-factor authentication.',
    'settings.enable2fa': 'Enable Two-Factor Authentication',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.updatePassword': 'Update Password',
    'settings.notifications': 'Notifications',
    'settings.notificationsDescription': 'Manage your notification preferences.',
    'settings.securityEmails': 'Security Emails',
    'settings.apiAlerts': 'API Usage Alerts',
    'settings.newsletter': 'Newsletter & Updates',
    'settings.savePreferences': 'Save Preferences',
    // Admin page
    'admin.accessDenied': 'Access Denied',
    'admin.adminOnly': 'This page is accessible to administrators only.',
    'admin.totalUsers': 'Total Users',
    'admin.totalApis': 'Total APIs',
    'admin.totalCalls': 'Total Calls',
    'admin.activeUsers': 'Active Users',
    'admin.lastMonth': 'since last month',
    'admin.lastWeek': 'since last week',
    'admin.vsLastMonth': 'from last month',
    'admin.allUsers': 'of all users',
    'admin.userManagement': 'User Management',
    'admin.userManagementDescription': 'Manage all users registered in the system.',
    'admin.systemSettings': 'System Settings',
    'admin.table.userName': 'User Name',
    'admin.table.email': 'Email',
    'admin.table.role': 'Role',
    'admin.table.status': 'Status',
    'admin.table.joinDate': 'Join Date',
    'admin.role.admin': 'Administrator',
    'admin.role.user': 'Regular User',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.editButton': 'Edit',
    // Admin External API Management
    'admin.externalApi.title': 'External API Management',
    'admin.externalApi.description': 'Register and manage external APIs for custom API creation',
    'admin.externalApi.form.title': 'Register New API',
    'admin.externalApi.form.name': 'API Name',
    'admin.externalApi.form.namePlaceholder': 'e.g. Housing Statistics',
    'admin.externalApi.form.description': 'API Description',
    'admin.externalApi.form.descriptionPlaceholder': 'e.g. (Population and Housing Census) Housing statistics API',
    'admin.externalApi.form.issuer': 'API Issuer',
    'admin.externalApi.form.issuerPlaceholder': 'e.g. SGIS',
    'admin.externalApi.form.credentialId': 'Credential ID',
    'admin.externalApi.form.credentialIdPlaceholder': 'e.g. SGIS',
    'admin.externalApi.form.url': 'API URL',
    'admin.externalApi.form.urlPlaceholder': 'https://sgisapi.kostat.go.kr/OpenAPI3/stats/house.json',
    'admin.externalApi.form.httpMethod': 'HTTP Method',
    'admin.externalApi.form.registering': 'Registering...',
    'admin.externalApi.form.registerButton': 'Register API',
    'admin.externalApi.parameters.title': 'Parameters',
    'admin.externalApi.parameters.count': '',
    'admin.externalApi.parameters.add': 'Add Parameter',
    'admin.externalApi.parameters.required': 'Required',
    'admin.externalApi.parameters.form.name': 'Parameter Name',
    'admin.externalApi.parameters.form.namePlaceholder': 'e.g. accessToken',
    'admin.externalApi.parameters.form.type': 'Type',
    'admin.externalApi.parameters.form.description': 'Description',
    'admin.externalApi.parameters.form.descriptionPlaceholder': 'e.g. Access key',
    'admin.externalApi.parameters.form.defaultValue': 'Default Value (Optional)',
    'admin.externalApi.parameters.form.defaultValuePlaceholder': 'Enter default value',
    'admin.externalApi.parameters.form.requiredParam': 'Required Parameter',
    'admin.externalApi.parameters.form.addButton': 'Add',
    'admin.externalApi.parameters.form.cancelButton': 'Cancel',
    'admin.externalApi.list.title': 'Registered External APIs',
    'admin.externalApi.list.count': '',
    'admin.externalApi.list.empty': 'No registered external APIs',
    'admin.externalApi.list.active': 'Active',
    'admin.externalApi.list.inactive': 'Inactive',
    'admin.externalApi.list.registeredDate': 'Registered Date',
    'admin.externalApi.validation.nameRequired': 'Please enter API name',
    'admin.externalApi.validation.urlRequired': 'Please enter API URL',
    'admin.externalApi.validation.urlInvalid': 'Invalid URL format',
    'admin.externalApi.validation.issuerRequired': 'Please enter API issuer',
    'admin.externalApi.validation.credentialRequired': 'Please enter Credential ID',
    'admin.externalApi.validation.nameExists': 'API name already exists',
    'admin.externalApi.success.registered': 'External API registered successfully',
    'admin.externalApi.success.registeredAlert': 'External API registered successfully!',
    'admin.externalApi.success.deleted': 'External API deleted successfully',
    'admin.externalApi.success.deletedAlert': 'External API deleted successfully!',
    'admin.externalApi.error.registrationFailed': 'External API registration failed:',
    'admin.externalApi.error.registrationAlert': 'Failed to register external API. Please try again.',
    'admin.externalApi.error.deletionFailed': 'External API deletion failed:',
    'admin.externalApi.error.deletionAlert': 'Failed to delete external API. Please try again.',
    'admin.externalApi.confirm.delete': 'Do you want to delete this API?',
    // Time units and actions (for monitoring page)
    'time.minutesAgo': 'minutes ago',
    'time.hoursAgo': 'hours ago',
    'time.daysAgo': 'days ago',
    'time.weeksAgo': 'weeks ago',
    'action.createProduct': '"Product Feed" API created',
    'action.createKey': 'New key created for "Weather API"',
    'action.deleteApi': '"Legacy User Service" API deleted',
    'action.updateSettings': '"Product Feed" settings updated',
    'action.userLogin': 'User login',
    // Custom API creation form
    'suggestions.dataDescription': 'Data Description',
    'suggestions.examplePlaceholder': 'e.g. "Global university rankings, tuition fees, and location data"',
    'suggestions.createButton': 'Generate',
    'suggestions.helpText': 'Please provide a clear and concise description of the data you are looking for.',
    'suggestions.recommendedTitle': 'Recommended APIs',
    'suggestions.recommendedDescription': 'Here are some APIs that match your requirements.',
    'suggestions.noResultsTitle': 'No Results Found',
    'suggestions.noResultsDescription': 'The AI could not find APIs for your query. Try changing your description and try again.',
    'suggestions.errorTitle': 'An error occurred.',
    'suggestions.errorDescription': 'Failed to generate API. Please try again later.',
    // API Board sample data
    'api.movieRecommendation': 'Movie Recommendation API',
    'api.movieRecommendationDesc': 'Personal preference-based movie recommendation system',
    'api.cryptoPriceTracker': 'Cryptocurrency Price Tracker',
    'api.cryptoPriceTrackerDesc': 'Real-time cryptocurrency price tracking API',
    'api.socialMediaAnalyzer': 'Social Media Analyzer',
    'api.socialMediaAnalyzerDesc': 'SNS post sentiment analysis and trend identification',
    'api.deliveryOptimizer': 'Food Delivery Optimizer',
    'api.deliveryOptimizerDesc': 'Delivery route optimization and time prediction',
    // API Categories
    'apiCatalog.title': 'Government API Catalog',
    'apiCatalog.subtitle': 'Access diverse public data APIs from Korean government agencies in one place',
    'apiCatalog.cta': 'Explore All APIs',
    'category.culture': 'Culture·Tourism',
    'category.disaster': 'Disaster·Safety',
    'category.agriculture': 'Agriculture·Livestock',
    'category.realestate': 'Real Estate·Construction',
    'category.economy': 'Economy·Finance',
    'category.employment': 'Employment·Jobs',
    'category.environment': 'Environment·Weather',
    'category.transport': 'Transportation·Regional',
    'category.legal': 'Legal·Patents',
    'category.education': 'Education·Medical',
    'category.nature': 'Nature·Leisure',
    'api.performance': 'Performance Exhibition Info',
    'api.performance.data': 'Performance, exhibition, cultural facility information',
    'api.tourism': 'Tourism Information',
    'api.tourism.data': 'Domestic tourist attractions, accommodation, restaurants, festivals, travel courses',
    'api.wildfire': 'Wildfire History',
    'api.wildfire.data': 'Wildfire occurrence and suppression status',
    'api.fire': 'Fire Incident Information',
    'api.fire.data': 'Fire incident statistics, fire station information',
    'api.livestock': 'Livestock Traceability',
    'api.livestock.data': 'Livestock history, agricultural product safety information',
    'api.fishery': 'Fishery Price Information',
    'api.fishery.data': 'Fishery prices, catch volume information',
    'api.townhouse': 'Townhouse Transaction Prices',
    'api.townhouse.data': 'Townhouse transaction information (contract amount, area, floors, etc.)',
    'api.apartment': 'Apartment Sale Prices',
    'api.apartment.data': 'Apartment transaction information',
    'api.vehicle': 'Vehicle Registration Info',
    'api.vehicle.data': 'Comprehensive vehicle information based on registration number',
    'api.business': 'Business Registration Status',
    'api.business.data': 'Business registration status, closure information',
    'api.ecos': 'Bank of Korea ECOS',
    'api.ecos.data': 'Economic statistics, exchange rates, interest rates',
    'api.dart': 'DART Disclosure Info',
    'api.dart.data': 'Listed company disclosure information, financial statements, business reports',
    'api.trade': 'Import/Export Statistics',
    'api.trade.data': 'Import/export statistics, customs information',
    'api.trader': 'Trading Company Info',
    'api.trader.data': 'Annual trade statistics for trading companies',
    'api.worknet': 'WorkNet Job Information',
    'api.worknet.data': 'Job search information',
    'api.publicjob': 'Public Employment Info',
    'api.publicjob.data': 'Public institution recruitment information',
    'api.venture': 'SME Venture 24',
    'api.venture.data': 'Small and medium venture company support program announcements',
    'api.airpollution': 'Air Pollution Information',
    'api.airpollution.data': 'Fine dust, air quality information',
    'api.weather': 'Weather Information',
    'api.weather.data': 'Ultra-short term observations, short-term forecasts',
    'api.earthquake': 'Earthquake Information',
    'api.earthquake.data': 'Earthquake occurrence information, tsunami information',
    'api.subway': 'Subway Real-time Arrival',
    'api.subway.data': 'Real-time subway arrival information',
    'api.sgis': 'SGIS Statistical Information',
    'api.sgis.data': 'Map-based demographic information, regional statistics, etc.',
    'api.law': 'National Legal Information',
    'api.law.data': 'Legal information, case law information',
    'api.patent': 'Patent Information',
    'api.patent.data': 'Patent, utility model, design, trademark information',
    'api.neis': 'NEIS',
    'api.neis.data': 'School information, meal information',
    'api.hospital': 'Hospital Information',
    'api.hospital.data': 'Basic information of hospitals and medical institutions',
    'api.medicine': 'Medicine Information',
    'api.medicine.data': 'Medicine information, food safety information',
    'api.mountain': 'Mountain Trail Information',
    'api.mountain.data': 'Mountain trail information, recreational forest information',
    'api.safety': 'Overseas Safety Information',
    'api.safety.data': 'Travel warnings, country-specific safety information',
  },
  ja: {
    'theme.light': 'ライト',
    'theme.dark': 'ダーク',
    'theme.toggle': 'テーマ切り替え',
    'language.toggle': '言語切り替え',
    'nav.features': '機能',
    'nav.pricing': '料金',
    'nav.docs': 'ドキュメント',
    'nav.signin': 'サインイン',
    'nav.getstarted': 'はじめる',
    'hero.title': '統合された',
    'hero.subtitle': 'APIを体験してください',
    'hero.description': '複数のパブリックAPIを単一の統合インターフェースで接続し、開発を簡素化します。より速く構築し、より簡単に統合できます。',
    'hero.cta': 'はじめる',
    'hero.learn': '詳細を見る',
    'features.title': '機能',
    'features.description': 'APIを効率的に接続・管理するために必要なすべて。',
    'feature.integration.title': 'API統合',
    'feature.integration.description': '複数のパブリックAPIを単一のインターフェースで統合します。',
    'feature.performance.title': '高速処理',
    'feature.performance.description': '最適化されたパフォーマンスで高速データ処理を提供します。',
    'feature.security.title': '安全な接続',
    'feature.security.description': 'セキュリティが強化された安全なAPI接続を保証します。',
    'footer.built': 'API Bridgeチームによって構築。ソースコードは',
    'footer.github': 'GitHub',
    'footer.available': 'で利用可能です。',
    'brand': 'APIブリッジ',
    // Dashboard navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.apiBoard': 'APIボード',
    'nav.suggestions': 'カスタムAPI作成',
    'nav.monitoring': 'モニタリング',
    'nav.settings': '設定',
    'nav.admin': '管理者',
    'nav.menu.toggle': 'ナビゲーションメニュー切り替え',
    // Dashboard stats
    'dashboard.stats.totalApis': '総API数',
    'dashboard.stats.activeKeys': 'アクティブキー',
    'dashboard.stats.totalCalls': '総呼び出し数（30日）',
    'dashboard.stats.uptime': '稼働時間',
    'dashboard.stats.lastMonth': '先月以降',
    'dashboard.stats.lastWeek': '先週以降',
    'dashboard.stats.vsLastMonth': '先月比',
    'dashboard.stats.allActiveApis': 'すべてのアクティブAPIで',
    // Dashboard API table
    'dashboard.myApis': 'マイAPI',
    'dashboard.myApis.description': 'カスタムデータソースAPIを管理します。',
    'dashboard.createApi': 'API作成',
    'dashboard.table.apiName': 'API名',
    'dashboard.table.status': 'ステータス',
    'dashboard.table.calls': '呼び出し数（30日）',
    'dashboard.table.successRate': '成功率',
    'dashboard.table.sharing': '共有',
    'dashboard.table.actions': 'アクション',
    'dashboard.badge.imported': 'インポートAPI',
    'dashboard.badge.myApi': 'マイAPI',
    'dashboard.originalAuthor': '元の作成者',
    'dashboard.status.active': 'アクティブ',
    'dashboard.status.inactive': '非アクティブ',
    'dashboard.status.error': 'エラー',
    'dashboard.share.sharing': '共有中',
    'dashboard.share.share': '共有',
    'dashboard.share.imported': 'インポート済み',
    // API Detail Modal
    'dashboard.modal.basicInfo': '基本情報',
    'dashboard.modal.apiPath': 'APIパス',
    'dashboard.modal.status': 'ステータス',
    'dashboard.modal.totalCalls': '総呼び出し数',
    'dashboard.modal.successRate': '成功率',
    'dashboard.modal.parameters': 'パラメーター',
    'dashboard.modal.noParameters': 'パラメーターがありません。',
    'dashboard.modal.required': '必須',
    'dashboard.modal.originalAuthor': '元の作成者',
    'dashboard.modal.sharedBy': 'このAPIは',
    'dashboard.menu.toggle': 'メニュー切り替え',
    'dashboard.menu.actions': 'アクション',
    'dashboard.menu.viewAnalytics': '分析を表示',
    'dashboard.menu.keyManagement': 'キー管理',
    'dashboard.menu.settings': '設定',
    'dashboard.menu.apiKey': 'APIキー',
    // User menu
    'user.menu.myAccount': 'マイアカウント',
    'user.menu.settings': '設定',
    'user.menu.support': 'サポート',
    'user.menu.logout': 'ログアウト',
    'user.menu.toggle': 'ユーザーメニュー切り替え',
    // Sample API data (for demo)
    'api.weather': '天気データAPI',
    'api.stockMarket': '株式市場フィード',
    'api.locationService': 'ユーザー位置情報サービス',
    'api.productCatalog': '製品カタログAPI',
    'api.paymentGateway': '決済ゲートウェイブリッジ',
    // Pricing page
    'pricing.title': 'シンプルで透明な料金',
    'pricing.subtitle': 'あなたのニーズに合ったプランを選択し、今すぐ構築を開始しましょう。',
    'pricing.free.title': '無料',
    'pricing.free.description': '個人プロジェクトや学習を始めるのに最適です。',
    'pricing.free.cta': '無料で始める',
    'pricing.pro.title': 'プロ',
    'pricing.pro.description': '強力な機能が必要な専門家やチームのためのプランです。',
    'pricing.pro.cta': 'プロプランを開始',
    'pricing.pro.popular': '最も人気',
    'pricing.pro.price': '¥2,800',
    'pricing.pro.period': '/月',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API作成',
    'pricing.feature.apiCalls.free': '月10,000回のAPI呼び出し',
    'pricing.feature.support.free': 'コミュニティサポート',
    'pricing.feature.apiCreation.pro': '無制限API作成',
    'pricing.feature.apiCalls.pro': '月1,000,000回のAPI呼び出し',
    'pricing.feature.ai': 'AI+機能',
    'pricing.feature.support.pro': '優先メールサポート',
    'pricing.feature.analytics': '高度な分析機能',
    'pricing.footer': '© 2024 APIブリッジ。すべての権利を保有。',
    // Login page
    'login.title': 'APIブリッジ',
    'login.description': 'アカウントにサインインするには、下記にメールアドレスを入力してください',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.forgotPassword': 'パスワードをお忘れですか？',
    'login.signIn': 'サインイン',
    'login.signInGoogle': 'Googleでサインイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.signUp': 'サインアップ',
    'login.emailPlaceholder': 'm@example.com',
    // API Board page
    'apiBoard.myShared': 'シェアしたキー',
    'apiBoard.imported': 'インポートしたキー',
    'apiBoard.totalBoard': '総ボードキー',
    'apiBoard.thisMonth': '今月',
    'apiBoard.thisWeek': '今週',
    'apiBoard.sharedApis': '共有API',
    'apiBoard.description': 'コミュニティで共有されたカスタムAPIを探索し、使用してください。',
    'apiBoard.searchPlaceholder': 'API名、説明、または作者で検索...',
    'apiBoard.table.apiName': 'API名',
    'apiBoard.table.author': '作者',
    'apiBoard.table.description': '説明',
    'apiBoard.table.usageCount': '使用回数',
    'apiBoard.table.sharedDate': '共有日',
    'apiBoard.importButton': 'インポート',
    'apiBoard.noResults': '検索結果がありません',
    'apiBoard.noResultsDescription': '別の検索語を試してください。',
    'apiBoard.importConfirmTitle': 'APIインポート確認',
    'apiBoard.importConfirmMessage': 'をダッシュボードにインポートしますか？',
    'apiBoard.importConfirmDescription': 'インポート後は、API一覧で確認できます。',
    'apiBoard.importConfirmYes': 'はい',
    'apiBoard.importConfirmCancel': 'キャンセル',
    // Custom API Creation page
    'suggestions.title': 'カスタムAPI作成',
    'suggestions.description': '必要なデータを説明すると、AIがカスタムAPIの作成を支援します。',
    // Monitoring page
    'monitoring.systemStatus': 'システムステータス',
    'monitoring.statusHealthy': '程度',
    'monitoring.lastCheck': '最後のチェック',
    'monitoring.apiSources': 'APIソース',
    'monitoring.connectedHealthy': '接続されていて健全',
    'monitoring.activeUsers': 'アクティブユーザー',
    'monitoring.onlineLast15': '過去15分間でオンライン',
    'monitoring.securityAlerts': 'セキュリティアラート',
    'monitoring.noCriticalAlerts': '今日は重要なアラートはありません',
    'monitoring.grafanaDashboard': 'Grafanaダッシュボード',
    'monitoring.grafanaDescription': 'リアルタイムシステムメトリックとパフォーマンス。',
    'monitoring.grafanaEmbed': 'Grafanaダッシュボードがここに埋め込まれます',
    'monitoring.kibanaDashboard': 'Kibanaダッシュボード',
    'monitoring.kibanaDescription': 'ログ解析とアプリケーショントレーシング。',
    'monitoring.kibanaEmbed': 'Kibanaダッシュボードがここに埋め込まれます',
    'monitoring.userActivity': 'ユーザー活動ストリーム',
    'monitoring.userActivityDescription': 'プラットフォーム全体の最近のユーザー活動の概要。',
    'monitoring.table.user': 'ユーザー',
    'monitoring.table.action': 'アクション',
    'monitoring.table.timestamp': 'タイムスタンプ',
    'monitoring.table.ipAddress': 'IPアドレス',
    // Settings page
    'settings.profile': 'プロフィール',
    'settings.profileDescription': '個人情報を管理します。',
    'settings.name': '名前',
    'settings.email': 'メールアドレス',
    'settings.save': '保存',
    'settings.security': 'セキュリティ',
    'settings.securityDescription': 'パスワードと二段階認証を管理します。',
    'settings.enable2fa': '二段階認証を有効にする',
    'settings.currentPassword': '現在のパスワード',
    'settings.newPassword': '新しいパスワード',
    'settings.updatePassword': 'パスワードを更新',
    'settings.notifications': '通知',
    'settings.notificationsDescription': '通知の設定を管理します。',
    'settings.securityEmails': 'セキュリティメール',
    'settings.apiAlerts': 'API使用量アラート',
    'settings.newsletter': 'ニュースレターとアップデート',
    'settings.savePreferences': '設定を保存',
    // Admin page
    'admin.accessDenied': 'アクセスが拒否されました',
    'admin.adminOnly': 'このページは管理者のみアクセスできます。',
    'admin.totalUsers': '総ユーザー数',
    'admin.totalApis': '総 API 数',
    'admin.totalCalls': '総呼び出し数',
    'admin.activeUsers': 'アクティブユーザー',
    'admin.lastMonth': '先月以降',
    'admin.lastWeek': '先週以降',
    'admin.vsLastMonth': '先月比',
    'admin.allUsers': '全ユーザー中',
    'admin.userManagement': 'ユーザー管理',
    'admin.userManagementDescription': 'システムに登録されたすべてのユーザーを管理できます。',
    'admin.systemSettings': 'システム設定',
    'admin.table.userName': 'ユーザー名',
    'admin.table.email': 'メールアドレス',
    'admin.table.role': '権限',
    'admin.table.status': 'ステータス',
    'admin.table.joinDate': '登録日',
    'admin.role.admin': '管理者',
    'admin.role.user': '一般ユーザー',
    'admin.status.active': 'アクティブ',
    'admin.status.inactive': '非アクティブ',
    'admin.editButton': '編集',
    // Time units and actions (for monitoring page)
    'time.minutesAgo': '分前',
    'time.hoursAgo': '時間前',
    'time.daysAgo': '日前',
    'time.weeksAgo': '週前',
    'action.createProduct': '"製品フィード" API作成',
    'action.createKey': '"天気API"の新しいキー作成',
    'action.deleteApi': '"旧ユーザーサービス" API削除',
    'action.updateSettings': '"製品フィード" 設定更新',
    'action.userLogin': 'ユーザーログイン',
    // Custom API creation form
    'suggestions.dataDescription': 'データ説明',
    'suggestions.examplePlaceholder': '例: "世界の大学ランキング、学費、位置データ"',
    'suggestions.createButton': '生成する',
    'suggestions.helpText': '探しているデータについて明確で簡潔な説明を提供してください。',
    'suggestions.recommendedTitle': '推奨API',
    'suggestions.recommendedDescription': 'あなたの要求に合うAPIは以下の通りです。',
    'suggestions.noResultsTitle': '結果が見つかりません',
    'suggestions.noResultsDescription': 'AIがあなたのクエリに対するAPIを見つけられませんでした。説明を変更して再度お試しください。',
    'suggestions.errorTitle': 'エラーが発生しました。',
    'suggestions.errorDescription': 'APIの生成に失敗しました。後で再度お試しください。',
    // API Board sample data
    'api.movieRecommendation': '映画推薦API',
    'api.movieRecommendationDesc': '個人の好みに基づいた映画推薦システム',
    'api.cryptoPriceTracker': '暗号資産価格トラッカー',
    'api.cryptoPriceTrackerDesc': 'リアルタイム暗号資産価格追跡API',
    'api.socialMediaAnalyzer': 'ソーシャルメディア分析器',
    'api.socialMediaAnalyzerDesc': 'SNS投稿の感情分析とトレンド把握',
    'api.deliveryOptimizer': '食品デリバリー最適化',
    'api.deliveryOptimizerDesc': 'デリバリールート最適化と時間予測',
  },
  zh: {
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.toggle': '切换主题',
    'language.toggle': '切换语言',
    'nav.features': '功能',
    'nav.pricing': '价格',
    'nav.docs': '文档',
    'nav.signin': '登录',
    'nav.getstarted': '开始',
    'hero.title': '体验统一的',
    'hero.subtitle': 'API集成',
    'hero.description': '通过单一统一接口连接多个公共API，简化您的开发。更快构建，更轻松集成。',
    'hero.cta': '开始',
    'hero.learn': '了解更多',
    'features.title': '功能',
    'features.description': '高效连接和管理API所需的一切。',
    'feature.integration.title': 'API集成',
    'feature.integration.description': '通过单一接口集成多个公共API。',
    'feature.performance.title': '快速处理',
    'feature.performance.description': '提供优化性能的快速数据处理。',
    'feature.security.title': '安全连接',
    'feature.security.description': '确保增强安全性的安全API连接。',
    'footer.built': '由API Bridge团队构建。源代码可在',
    'footer.github': 'GitHub',
    'footer.available': '上获得。',
    'brand': 'API桥接',
    // Dashboard navigation
    'nav.dashboard': '仪表板',
    'nav.apiBoard': 'API面板',
    'nav.suggestions': '自定义API创建',
    'nav.monitoring': '监控',
    'nav.settings': '设置',
    'nav.admin': '管理员',
    'nav.menu.toggle': '切换导航菜单',
    // Dashboard stats
    'dashboard.stats.totalApis': '总API数',
    'dashboard.stats.activeKeys': '活跃密钥',
    'dashboard.stats.totalCalls': '总调用数（30天）',
    'dashboard.stats.uptime': '正常运行时间',
    'dashboard.stats.lastMonth': '自上月以来',
    'dashboard.stats.lastWeek': '自上周以来',
    'dashboard.stats.vsLastMonth': '与上月相比',
    'dashboard.stats.allActiveApis': '在所有活跃API中',
    // Dashboard API table
    'dashboard.myApis': '我的API',
    'dashboard.myApis.description': '管理您的自定义数据源API。',
    'dashboard.createApi': '创建API',
    'dashboard.table.apiName': 'API名称',
    'dashboard.table.status': '状态',
    'dashboard.table.calls': '调用数（30天）',
    'dashboard.table.successRate': '成功率',
    'dashboard.table.sharing': '共享',
    'dashboard.table.actions': '操作',
    'dashboard.badge.imported': '导入的API',
    'dashboard.badge.myApi': '我的API',
    'dashboard.originalAuthor': '原作者',
    'dashboard.status.active': '活跃',
    'dashboard.status.inactive': '非活跃',
    'dashboard.status.error': '错误',
    'dashboard.share.sharing': '共享中',
    'dashboard.share.share': '共享',
    'dashboard.share.imported': '已导入',
    // API Detail Modal
    'dashboard.modal.basicInfo': '基本信息',
    'dashboard.modal.apiPath': 'API路径',
    'dashboard.modal.status': '状态',
    'dashboard.modal.totalCalls': '总调用数',
    'dashboard.modal.successRate': '成功率',
    'dashboard.modal.parameters': '参数',
    'dashboard.modal.noParameters': '无可用参数。',
    'dashboard.modal.required': '必需',
    'dashboard.modal.originalAuthor': '原作者',
    'dashboard.modal.sharedBy': '此API由',
    'dashboard.menu.toggle': '切换菜单',
    'dashboard.menu.actions': '操作',
    'dashboard.menu.viewAnalytics': '查看分析',
    'dashboard.menu.keyManagement': '密钥管理',
    'dashboard.menu.settings': '设置',
    'dashboard.menu.apiKey': 'API密钥',
    // User menu
    'user.menu.myAccount': '我的账户',
    'user.menu.settings': '设置',
    'user.menu.support': '支持',
    'user.menu.logout': '退出登录',
    'user.menu.toggle': '切换用户菜单',
    // Sample API data (for demo)
    'api.weather': '天气数据API',
    'api.stockMarket': '股票市场订阅',
    'api.locationService': '用户位置服务',
    'api.productCatalog': '产品目录API',
    'api.paymentGateway': '支付网关桥接',
    // Pricing page
    'pricing.title': '简单透明的价格',
    'pricing.subtitle': '选择适合您需求的计划，立即开始构建。',
    'pricing.free.title': '免费',
    'pricing.free.description': '非常适合个人项目和学习入门。',
    'pricing.free.cta': '免费开始',
    'pricing.pro.title': '专业版',
    'pricing.pro.description': '为需要强大功能的专业人士和团队设计。',
    'pricing.pro.cta': '开始专业版计划',
    'pricing.pro.popular': '最受欢迎',
    'pricing.pro.price': '¥150',
    'pricing.pro.period': '/月',
    // Pricing features
    'pricing.feature.apiCreation.free': '1个API创建',
    'pricing.feature.apiCalls.free': '每月10,000次API调用',
    'pricing.feature.support.free': '社区支持',
    'pricing.feature.apiCreation.pro': '无限制API创建',
    'pricing.feature.apiCalls.pro': '每月1,000,000次API调用',
    'pricing.feature.ai': 'AI+功能',
    'pricing.feature.support.pro': '优先邮件支持',
    'pricing.feature.analytics': '高级分析功能',
    'pricing.footer': '© 2024 API桥接。保留所有权利。',
    // Login page
    'login.title': 'API桥接',
    'login.description': '请在下方输入您的邮箱以登录您的账户',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.forgotPassword': '忘记密码？',
    'login.signIn': '登录',
    'login.signInGoogle': '使用Google登录',
    'login.noAccount': '没有账户？',
    'login.signUp': '注册',
    'login.emailPlaceholder': 'm@example.com',
    // API Board page
    'apiBoard.myShared': '我共享的密钥',
    'apiBoard.imported': '导入的密钥',
    'apiBoard.totalBoard': '总面板密钥',
    'apiBoard.thisMonth': '本月',
    'apiBoard.thisWeek': '本周',
    'apiBoard.sharedApis': '共享API',
    'apiBoard.description': '探索并使用社区共享的自定义API。',
    'apiBoard.searchPlaceholder': '通过API名称、描述或作者搜索...',
    'apiBoard.table.apiName': 'API名称',
    'apiBoard.table.author': '作者',
    'apiBoard.table.description': '描述',
    'apiBoard.table.usageCount': '使用次数',
    'apiBoard.table.sharedDate': '共享日期',
    'apiBoard.importButton': '导入',
    'apiBoard.noResults': '没有搜索结果',
    'apiBoard.noResultsDescription': '请尝试不同的搜索词。',
    'apiBoard.importConfirmTitle': '确认导入API',
    'apiBoard.importConfirmMessage': '到您的仪表板吗？',
    'apiBoard.importConfirmDescription': '导入后，您可以在API列表中查看。',
    'apiBoard.importConfirmYes': '是',
    'apiBoard.importConfirmCancel': '取消',
    // Custom API Creation page
    'suggestions.title': '自定义API创建',
    'suggestions.description': '描述您需要的数据，AI将帮助创建自定义API。',
    // Monitoring page
    'monitoring.systemStatus': '系统状态',
    'monitoring.statusHealthy': '健康',
    'monitoring.lastCheck': '最后检查',
    'monitoring.apiSources': 'API源',
    'monitoring.connectedHealthy': '已连接且健康',
    'monitoring.activeUsers': '活跃用户',
    'monitoring.onlineLast15': '过15分钟内在线',
    'monitoring.securityAlerts': '安全警报',
    'monitoring.noCriticalAlerts': '今天没有关键警报',
    'monitoring.grafanaDashboard': 'Grafana仪表板',
    'monitoring.grafanaDescription': '实时系统指标和性能。',
    'monitoring.grafanaEmbed': 'Grafana仪表板将在这里嵌入',
    'monitoring.kibanaDashboard': 'Kibana仪表板',
    'monitoring.kibanaDescription': '日志分析和应用追踪。',
    'monitoring.kibanaEmbed': 'Kibana仪表板将在这里嵌入',
    'monitoring.userActivity': '用户活动流',
    'monitoring.userActivityDescription': '平台上最近用户活动的概览。',
    'monitoring.table.user': '用户',
    'monitoring.table.action': '操作',
    'monitoring.table.timestamp': '时间戳',
    'monitoring.table.ipAddress': 'IP地址',
    // Settings page
    'settings.profile': '个人资料',
    'settings.profileDescription': '管理您的个人信息。',
    'settings.name': '姓名',
    'settings.email': '邮箱',
    'settings.save': '保存',
    'settings.security': '安全',
    'settings.securityDescription': '管理您的密码和双因子身份验证。',
    'settings.enable2fa': '启用双因子身份验证',
    'settings.currentPassword': '当前密码',
    'settings.newPassword': '新密码',
    'settings.updatePassword': '更新密码',
    'settings.notifications': '通知',
    'settings.notificationsDescription': '管理您的通知偏好。',
    'settings.securityEmails': '安全邮件',
    'settings.apiAlerts': 'API使用警报',
    'settings.newsletter': '通讯和更新',
    'settings.savePreferences': '保存偏好',
    // Admin page
    'admin.accessDenied': '访问被拒绝',
    'admin.adminOnly': '只有管理员可以访问此页面。',
    'admin.totalUsers': '总用户数',
    'admin.totalApis': '总API数',
    'admin.totalCalls': '总调用数',
    'admin.activeUsers': '活跃用户',
    'admin.lastMonth': '自上月以来',
    'admin.lastWeek': '自上周以来',
    'admin.vsLastMonth': '与上月相比',
    'admin.allUsers': '在所有用户中',
    'admin.userManagement': '用户管理',
    'admin.userManagementDescription': '管理系统中注册的所有用户。',
    'admin.systemSettings': '系统设置',
    'admin.table.userName': '用户名',
    'admin.table.email': '邮箱',
    'admin.table.role': '角色',
    'admin.table.status': '状态',
    'admin.table.joinDate': '加入日期',
    'admin.role.admin': '管理员',
    'admin.role.user': '普通用户',
    'admin.status.active': '活跃',
    'admin.status.inactive': '非活跃',
    'admin.editButton': '编辑',
    // Time units and actions (for monitoring page)
    'time.minutesAgo': '分钟前',
    'time.hoursAgo': '小时前',
    'time.daysAgo': '天前',
    'time.weeksAgo': '周前',
    'action.createProduct': '创建了“产品订阅”API',
    'action.createKey': '为“天气API”创建了新密钥',
    'action.deleteApi': '删除了“旧用户服务”API',
    'action.updateSettings': '更新了“产品订阅”设置',
    'action.userLogin': '用户登录',
    // Custom API creation form
    'suggestions.dataDescription': '数据描述',
    'suggestions.examplePlaceholder': '例：“全球大学排名、学费和位置数据”',
    'suggestions.createButton': '生成',
    'suggestions.helpText': '请提供您正在寻找的数据的清晰简洁的描述。',
    'suggestions.recommendedTitle': '推荐API',
    'suggestions.recommendedDescription': '以下是一些符合您要求的API。',
    'suggestions.noResultsTitle': '找不到结果',
    'suggestions.noResultsDescription': 'AI无法为您的查询找到API。请尝试更改您的描述并再试一次。',
    'suggestions.errorTitle': '发生了错误。',
    'suggestions.errorDescription': '生成API失败。请稍后再试。',
    // API Board sample data
    'api.movieRecommendation': '电影推荐API',
    'api.movieRecommendationDesc': '基于个人喜好的电影推荐系统',
    'api.cryptoPriceTracker': '加密货币价格跟踪器',
    'api.cryptoPriceTrackerDesc': '实时加密货币价格跟踪API',
    'api.socialMediaAnalyzer': '社交媒体分析器',
    'api.socialMediaAnalyzerDesc': '社交媒体帖子情感分析和趋势识别',
    'api.deliveryOptimizer': '美食外卖优化器',
    'api.deliveryOptimizerDesc': '外卖路线优化和时间预测',
  },
  ru: {
    'theme.light': 'Светлая',
    'theme.dark': 'Тёмная',
    'theme.toggle': 'Переключить тему',
    'language.toggle': 'Переключить язык',
    'nav.features': 'Функции',
    'nav.pricing': 'Цены',
    'nav.docs': 'Документация',
    'nav.signin': 'Войти',
    'nav.getstarted': 'Начать',
    'hero.title': 'Испытайте единое',
    'hero.subtitle': 'API-интеграцию',
    'hero.description': 'Упростите разработку, подключив несколько публичных API через единый унифицированный интерфейс. Создавайте быстрее, интегрируйте проще.',
    'hero.cta': 'Начать',
    'hero.learn': 'Узнать больше',
    'features.title': 'Функции',
    'features.description': 'Всё необходимое для эффективного подключения и управления API.',
    'feature.integration.title': 'API-интеграция',
    'feature.integration.description': 'Интегрируйте несколько публичных API через единый интерфейс.',
    'feature.performance.title': 'Быстрая обработка',
    'feature.performance.description': 'Обеспечивает быструю обработку данных с оптимизированной производительностью.',
    'feature.security.title': 'Безопасное соединение',
    'feature.security.description': 'Гарантирует безопасные API-соединения с усиленной защитой.',
    'footer.built': 'Создано командой API Bridge. Исходный код доступен на',
    'footer.github': 'GitHub',
    'footer.available': '.',
    'brand': 'API Мост',
    // Dashboard navigation
    'nav.dashboard': 'Панель управления',
    'nav.apiBoard': 'API-панель',
    'nav.suggestions': 'Создание пользовательских API',
    'nav.monitoring': 'Мониторинг',
    'nav.settings': 'Настройки',
    'nav.admin': 'Администратор',
    'nav.menu.toggle': 'Переключить навигационное меню',
    // Dashboard stats
    'dashboard.stats.totalApis': 'Всего API',
    'dashboard.stats.activeKeys': 'Активные ключи',
    'dashboard.stats.totalCalls': 'Всего вызовов (30 дней)',
    'dashboard.stats.uptime': 'Время работы',
    'dashboard.stats.lastMonth': 'с прошлого месяца',
    'dashboard.stats.lastWeek': 'с прошлой недели',
    'dashboard.stats.vsLastMonth': 'по сравнению с прошлым месяцем',
    'dashboard.stats.allActiveApis': 'по всем активным API',
    // Dashboard API table
    'dashboard.myApis': 'Мои API',
    'dashboard.myApis.description': 'Управляйте вашими пользовательскими API источников данных.',
    'dashboard.createApi': 'Создать API',
    'dashboard.table.apiName': 'Название API',
    'dashboard.table.status': 'Статус',
    'dashboard.table.calls': 'Вызовы (30 дней)',
    'dashboard.table.successRate': 'Успешность',
    'dashboard.table.sharing': 'Общий доступ',
    'dashboard.table.actions': 'Действия',
    'dashboard.badge.imported': 'Импортированный API',
    'dashboard.badge.myApi': 'Мой API',
    'dashboard.originalAuthor': 'Первоначальный автор',
    'dashboard.status.active': 'Активен',
    'dashboard.status.inactive': 'Неактивен',
    'dashboard.status.error': 'Ошибка',
    'dashboard.share.sharing': 'Общий доступ',
    'dashboard.share.share': 'Поделиться',
    'dashboard.share.imported': 'Импортирован',
    // API Detail Modal
    'dashboard.modal.basicInfo': 'Основная информация',
    'dashboard.modal.apiPath': 'Путь API',
    'dashboard.modal.status': 'Статус',
    'dashboard.modal.totalCalls': 'Всего вызовов',
    'dashboard.modal.successRate': 'Успешность',
    'dashboard.modal.parameters': 'Параметры',
    'dashboard.modal.noParameters': 'Параметры недоступны.',
    'dashboard.modal.required': 'Обязательно',
    'dashboard.modal.originalAuthor': 'Первоначальный автор',
    'dashboard.modal.sharedBy': 'Этот API предоставлен',
    'dashboard.menu.toggle': 'Переключить меню',
    'dashboard.menu.actions': 'Действия',
    'dashboard.menu.viewAnalytics': 'Просмотр аналитики',
    'dashboard.menu.keyManagement': 'Управление ключами',
    'dashboard.menu.settings': 'Настройки',
    'dashboard.menu.apiKey': 'API-ключ',
    // User menu
    'user.menu.myAccount': 'Мой аккаунт',
    'user.menu.settings': 'Настройки',
    'user.menu.support': 'Поддержка',
    'user.menu.logout': 'Выйти',
    'user.menu.toggle': 'Переключить пользовательское меню',
    // Sample API data (for demo)
    'api.weather': 'API данных о погоде',
    'api.stockMarket': 'Лента фондового рынка',
    'api.locationService': 'Сервис геолокации пользователя',
    'api.productCatalog': 'API каталога продуктов',
    'api.paymentGateway': 'Мост платёжного шлюза',
    // Pricing page
    'pricing.title': 'Простые и прозрачные цены',
    'pricing.subtitle': 'Выберите план, который подходит вашим потребностям, и начните создавать прямо сейчас.',
    'pricing.free.title': 'Бесплатно',
    'pricing.free.description': 'Идеально подходит для начала работы с личными проектами и обучения.',
    'pricing.free.cta': 'Начать бесплатно',
    'pricing.pro.title': 'Профессиональный',
    'pricing.pro.description': 'Для профессионалов и команд, которым нужны мощные функции.',
    'pricing.pro.cta': 'Начать профессиональный план',
    'pricing.pro.popular': 'Самый популярный',
    'pricing.pro.price': '2,200 ₽',
    'pricing.pro.period': '/мес',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 создание API',
    'pricing.feature.apiCalls.free': '10 000 API-вызовов в месяц',
    'pricing.feature.support.free': 'Поддержка сообщества',
    'pricing.feature.apiCreation.pro': 'Неограниченное создание API',
    'pricing.feature.apiCalls.pro': '1 000 000 API-вызовов в месяц',
    'pricing.feature.ai': 'AI+ функции',
    'pricing.feature.support.pro': 'Приоритетная поддержка по email',
    'pricing.feature.analytics': 'Расширенная аналитика',
    'pricing.footer': '© 2024 API Мост. Все права защищены.',
    // Login page
    'login.title': 'API Мост',
    'login.description': 'Введите ваш email ниже, чтобы войти в ваш аккаунт',
    'login.email': 'Email',
    'login.password': 'Пароль',
    'login.forgotPassword': 'Забыли пароль?',
    'login.signIn': 'Войти',
    'login.signInGoogle': 'Войти через Google',
    'login.noAccount': 'Нет аккаунта?',
    'login.signUp': 'Зарегистрироваться',
    'login.emailPlaceholder': 'm@example.com',
    // API Board page
    'apiBoard.myShared': 'Мои общие ключи',
    'apiBoard.imported': 'Импортированные ключи',
    'apiBoard.totalBoard': 'Общие ключи панели',
    'apiBoard.thisMonth': 'в этом месяце',
    'apiBoard.thisWeek': 'на этой неделе',
    'apiBoard.sharedApis': 'Общие API',
    'apiBoard.description': 'Исследуйте и используйте пользовательские API, предоставленные сообществом.',
    'apiBoard.searchPlaceholder': 'Поиск по названию API, описанию или автору...',
    'apiBoard.table.apiName': 'Название API',
    'apiBoard.table.author': 'Автор',
    'apiBoard.table.description': 'Описание',
    'apiBoard.table.usageCount': 'Количество использований',
    'apiBoard.table.sharedDate': 'Дата предоставления',
    'apiBoard.importButton': 'Импорт',
    'apiBoard.noResults': 'Нет результатов поиска',
    'apiBoard.noResultsDescription': 'Попробуйте другой поисковый запрос.',
    'apiBoard.importConfirmTitle': 'Подтвердить импорт API',
    'apiBoard.importConfirmMessage': ' в вашу панель управления?',
    'apiBoard.importConfirmDescription': 'После импорта вы сможете найти его в списке API.',
    'apiBoard.importConfirmYes': 'Да',
    'apiBoard.importConfirmCancel': 'Отмена',
    // Custom API Creation page
    'suggestions.title': 'Создание пользовательского API',
    'suggestions.description': 'Опишите необходимые данные, и AI поможет создать пользовательский API.',
    // Monitoring page
    'monitoring.systemStatus': 'Состояние системы',
    'monitoring.statusHealthy': 'Здоров',
    'monitoring.lastCheck': 'последняя проверка',
    'monitoring.apiSources': 'Источники API',
    'monitoring.connectedHealthy': 'подключено и здорово',
    'monitoring.activeUsers': 'Активные пользователи',
    'monitoring.onlineLast15': 'в сети за последние 15 минут',
    'monitoring.securityAlerts': 'Предупреждения безопасности',
    'monitoring.noCriticalAlerts': 'критических предупреждений сегодня нет',
    'monitoring.grafanaDashboard': 'Панель Grafana',
    'monitoring.grafanaDescription': 'Метрики системы в реальном времени и производительность.',
    'monitoring.grafanaEmbed': 'Панель Grafana будет встроена здесь',
    'monitoring.kibanaDashboard': 'Панель Kibana',
    'monitoring.kibanaDescription': 'Анализ логов и отслеживание приложений.',
    'monitoring.kibanaEmbed': 'Панель Kibana будет встроена здесь',
    'monitoring.userActivity': 'Поток активности пользователей',
    'monitoring.userActivityDescription': 'Обзор последней активности пользователей на платформе.',
    'monitoring.table.user': 'Пользователь',
    'monitoring.table.action': 'Действие',
    'monitoring.table.timestamp': 'Временная метка',
    'monitoring.table.ipAddress': 'IP-адрес',
    // Settings page
    'settings.profile': 'Профиль',
    'settings.profileDescription': 'Управляйте вашей личной информацией.',
    'settings.name': 'Имя',
    'settings.email': 'Email',
    'settings.save': 'Сохранить',
    'settings.security': 'Безопасность',
    'settings.securityDescription': 'Управляйте вашим паролем и двухфакторной аутентификацией.',
    'settings.enable2fa': 'Включить двухфакторную аутентификацию',
    'settings.currentPassword': 'Текущий пароль',
    'settings.newPassword': 'Новый пароль',
    'settings.updatePassword': 'Обновить пароль',
    'settings.notifications': 'Уведомления',
    'settings.notificationsDescription': 'Управляйте вашими настройками уведомлений.',
    'settings.securityEmails': 'Письма безопасности',
    'settings.apiAlerts': 'Предупреждения о использовании API',
    'settings.newsletter': 'Новостная рассылка и обновления',
    'settings.savePreferences': 'Сохранить настройки',
    // Admin page
    'admin.accessDenied': 'Доступ запрещен',
    'admin.adminOnly': 'Эта страница доступна только администраторам.',
    'admin.totalUsers': 'Общее количество пользователей',
    'admin.totalApis': 'Общее количество API',
    'admin.totalCalls': 'Общее количество вызовов',
    'admin.activeUsers': 'Активные пользователи',
    'admin.lastMonth': 'с прошлого месяца',
    'admin.lastWeek': 'с прошлой недели',
    'admin.vsLastMonth': 'с прошлого месяца',
    'admin.allUsers': 'из всех пользователей',
    'admin.userManagement': 'Управление пользователями',
    'admin.userManagementDescription': 'Управляйте всеми пользователями, зарегистрированными в системе.',
    'admin.systemSettings': 'Настройки системы',
    'admin.table.userName': 'Имя пользователя',
    'admin.table.email': 'Email',
    'admin.table.role': 'Роль',
    'admin.table.status': 'Состояние',
    'admin.table.joinDate': 'Дата регистрации',
    'admin.role.admin': 'Администратор',
    'admin.role.user': 'Обычный пользователь',
    'admin.status.active': 'Активный',
    'admin.status.inactive': 'Неактивный',
    'admin.editButton': 'Редактировать',
    // Time units and actions (for monitoring page)
    'time.minutesAgo': 'минут назад',
    'time.hoursAgo': 'часов назад',
    'time.daysAgo': 'дней назад',
    'time.weeksAgo': 'недель назад',
    'action.createProduct': 'Создан API "Лента продуктов"',
    'action.createKey': 'Создан новый ключ для "Погодное API"',
    'action.deleteApi': 'Удален API "Устаревший сервис пользователей"',
    'action.updateSettings': 'Обновлены настройки "Лента продуктов"',
    'action.userLogin': 'Вход пользователя',
    // Custom API creation form
    'suggestions.dataDescription': 'Описание данных',
    'suggestions.examplePlaceholder': 'напр.: "Мировые рейтинги университетов, стоимость обучения и данные о местоположении"',
    'suggestions.createButton': 'Создать',
    'suggestions.helpText': 'Пожалуйста, определите ясное и краткое описание данных, которые вы ищете.',
    'suggestions.recommendedTitle': 'Рекомендуемые API',
    'suggestions.recommendedDescription': 'Вот несколько API, которые соответствуют вашим требованиям.',
    'suggestions.noResultsTitle': 'Результаты не найдены',
    'suggestions.noResultsDescription': 'AI не смог найти API для вашего запроса. Попробуйте изменить описание и повторить попытку.',
    'suggestions.errorTitle': 'Произошла ошибка.',
    'suggestions.errorDescription': 'Не удалось сгенерировать API. Пожалуйста, повторите попытку позже.',
    // API Board sample data
    'api.movieRecommendation': 'API рекомендаций фильмов',
    'api.movieRecommendationDesc': 'Система рекомендаций фильмов на основе личных предпочтений',
    'api.cryptoPriceTracker': 'Отслеживатель цен криптовалют',
    'api.cryptoPriceTrackerDesc': 'API для отслеживания цен криптовалют в реальном времени',
    'api.socialMediaAnalyzer': 'Анализатор соцсетей',
    'api.socialMediaAnalyzerDesc': 'Анализ настроений постов в соцсетях и выявление трендов',
    'api.deliveryOptimizer': 'Оптимизатор доставки еды',
    'api.deliveryOptimizerDesc': 'Оптимизация маршрутов доставки и прогнозирование времени',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ko');

  // Load language from sessionStorage on initial load
  useEffect(() => {
    const savedLanguage = sessionStorage.getItem('language') as Language;
    if (savedLanguage && ['ko', 'en', 'ja', 'zh', 'ru'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to sessionStorage whenever it changes
  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    sessionStorage.setItem('language', newLanguage);
  };

  const t = useCallback((key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  }, [language]);

  // Helper function to translate dynamic content with fallback
  const translateIfExists = useCallback((key: string, fallback: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || fallback;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage: handleSetLanguage,
    t,
    translateIfExists
  }), [language, t, translateIfExists]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};