'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

// 한국어 / 영어 / 일본어 / 중국어 / 러시아어
type Language = 'ko' | 'en' | 'ja' | 'zh' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  // Helper for translating dynamic content (user-generated names, etc.)
  translateIfExists: (key: string, fallback: string) => string;
}

const translations = {
  ko: {
    'theme.light': '밝게',
    'theme.dark': '어둡게',
    'theme.toggle': '테마 변경',
    'language.toggle': '언어 변경',
    'nav.features': '기능',
    'nav.pricing': '가격',
    'nav.docs': '문서',
    'nav.signin': '로그인',
    'nav.getstarted': '시작하기',
    'hero.title': '하나로 통합된',
    'hero.subtitle': 'API를 경험해보세요',
    'hero.description': '여러 공공 API를 단일 통합 인터페이스를 통해 연결하여 개발을 간소화하세요. 더 빠르게 구축하고, 더 쉽게 통합하세요.',
    'hero.cta': '시작하기',
    'hero.learn': '더 알아보기',
    'features.title': '기능',
    'features.description': 'API를 효율적으로 연결하고 관리하는 데 필요한 모든 것.',
    'feature.integration.title': 'API 통합',
    'feature.integration.description': '여러 공공 API를 하나의 인터페이스로 통합합니다.',
    'feature.performance.title': '빠른 처리',
    'feature.performance.description': '최적화된 성능으로 빠른 데이터 처리를 제공합니다.',
    'feature.security.title': '안전한 연결',
    'feature.security.description': '보안이 강화된 안전한 API 연결을 보장합니다.',
    'footer.built': 'API Bridge 팀에서 제작. 소스 코드는',
    'footer.github': 'GitHub',
    'footer.available': '에서 확인할 수 있습니다.',
    'brand': 'API 브릿지',
    // Dashboard navigation
    'nav.dashboard': '대시보드',
    'nav.apiBoard': 'API 게시판',
    'nav.suggestions': '커스텀API 생성',
    'nav.monitoring': '모니터링',
    'nav.settings': '설정',
    'nav.menu.toggle': '탐색 메뉴 전환',
    // Dashboard stats
    'dashboard.stats.totalApis': '총 API',
    'dashboard.stats.activeKeys': '활성 키',
    'dashboard.stats.totalCalls': '총 호출 (30일)',
    'dashboard.stats.uptime': '가동 시간',
    'dashboard.stats.lastMonth': '지난달 이후',
    'dashboard.stats.lastWeek': '지난주 이후',
    'dashboard.stats.vsLastMonth': '지난달 대비',
    'dashboard.stats.allActiveApis': '모든 활성 API에서',
    // Dashboard API table
    'dashboard.myApis': '내 API',
    'dashboard.myApis.description': '사용자 지정 데이터 소스 API를 관리합니다.',
    'dashboard.createApi': 'API 생성',
    'dashboard.table.apiName': 'API 이름',
    'dashboard.table.status': '상태',
    'dashboard.table.calls': '호출 (30일)',
    'dashboard.table.successRate': '성공률',
    'dashboard.table.sharing': '공유',
    'dashboard.table.actions': '작업',
    'dashboard.badge.imported': '가져온 API',
    'dashboard.badge.myApi': '내 API',
    'dashboard.originalAuthor': '원작자',
    'dashboard.status.active': '활성',
    'dashboard.status.inactive': '비활성',
    'dashboard.status.error': '오류',
    'dashboard.share.sharing': '공유중',
    'dashboard.share.share': '공유하기',
    'dashboard.share.imported': '가져온 API',
    'dashboard.menu.toggle': '메뉴 전환',
    'dashboard.menu.actions': '작업',
    'dashboard.menu.viewAnalytics': '분석 보기',
    'dashboard.menu.keyManagement': '키 관리',
    'dashboard.menu.settings': '설정',
    'dashboard.menu.apiKey': 'API 키',
    // User menu
    'user.menu.myAccount': '내 계정',
    'user.menu.settings': '설정',
    'user.menu.support': '지원',
    'user.menu.logout': '로그아웃',
    'user.menu.toggle': '사용자 메뉴 전환',
    // Sample API data (for demo)
    'api.weather': '날씨 데이터 API',
    'api.stockMarket': '주식 시장 피드',
    'api.locationService': '사용자 위치정보 서비스',
    'api.productCatalog': '제품 카탈로그 API',
    'api.paymentGateway': '결제 게이트웨이 브릿지',
    // Pricing page
    'pricing.title': '간단하고 투명한 가격',
    'pricing.subtitle': '귀하의 필요에 맞는 플랜을 선택하고 지금 바로 구축을 시작하세요.',
    'pricing.free.title': 'Free',
    'pricing.free.description': '개인 프로젝트 및 학습용으로 시작하기에 좋습니다.',
    'pricing.free.cta': '무료로 시작하기',
    'pricing.pro.title': 'Pro',
    'pricing.pro.description': '강력한 기능이 필요한 전문가 및 팀을 위한 플랜입니다.',
    'pricing.pro.cta': 'Pro 플랜 시작하기',
    'pricing.pro.popular': '가장 인기있는',
    'pricing.pro.price': '₩9,990',
    'pricing.pro.period': '/월',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API 생성',
    'pricing.feature.apiCalls.free': '월 10,000건의 API 호출',
    'pricing.feature.support.free': '커뮤니티 지원',
    'pricing.feature.apiCreation.pro': '무제한 API 생성',
    'pricing.feature.apiCalls.pro': '월 1,000,000건의 API 호출',
    'pricing.feature.ai': 'AI+ 기능',
    'pricing.feature.support.pro': '우선 이메일 지원',
    'pricing.feature.analytics': '고급 분석 기능',
    'pricing.footer': '© 2024 API 브릿지. 모든 권리 보유.',
    // Login page
    'login.title': 'API 브릿지',
    'login.description': '계정에 로그인하려면 아래에 이메일을 입력하세요',
    'login.email': '이메일',
    'login.password': '비밀번호',
    'login.forgotPassword': '비밀번호를 잊으셨나요?',
    'login.signIn': '로그인',
    'login.signInGoogle': 'Google로 로그인',
    'login.noAccount': '계정이 없으신가요?',
    'login.signUp': '가입하기',
    'login.emailPlaceholder': 'm@example.com',
  },
  en: {
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.toggle': 'Toggle theme',
    'language.toggle': 'Toggle language',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.docs': 'Docs',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'hero.title': 'Experience Unified',
    'hero.subtitle': 'API Integration',
    'hero.description': 'Simplify your development by connecting multiple public APIs through a single, unified interface. Build faster, integrate easier.',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    'features.title': 'Features',
    'features.description': 'Everything you need to connect and manage your APIs efficiently.',
    'feature.integration.title': 'API Integration',
    'feature.integration.description': 'Integrate multiple public APIs through a single interface.',
    'feature.performance.title': 'Fast Processing',
    'feature.performance.description': 'Provides fast data processing with optimized performance.',
    'feature.security.title': 'Secure Connection',
    'feature.security.description': 'Ensures secure API connections with enhanced security.',
    'footer.built': 'Built by API Bridge team. The source code is available on',
    'footer.github': 'GitHub',
    'footer.available': '.',
    'brand': 'API Bridge',
    // Dashboard navigation
    'nav.dashboard': 'Dashboard',
    'nav.apiBoard': 'API Board',
    'nav.suggestions': 'Custom API Creation',
    'nav.monitoring': 'Monitoring',
    'nav.settings': 'Settings',
    'nav.menu.toggle': 'Toggle navigation menu',
    // Dashboard stats
    'dashboard.stats.totalApis': 'Total APIs',
    'dashboard.stats.activeKeys': 'Active Keys',
    'dashboard.stats.totalCalls': 'Total Calls (30d)',
    'dashboard.stats.uptime': 'Uptime',
    'dashboard.stats.lastMonth': 'since last month',
    'dashboard.stats.lastWeek': 'since last week',
    'dashboard.stats.vsLastMonth': 'from last month',
    'dashboard.stats.allActiveApis': 'across all active APIs',
    // Dashboard API table
    'dashboard.myApis': 'My APIs',
    'dashboard.myApis.description': 'Manage your custom data source APIs.',
    'dashboard.createApi': 'Create API',
    'dashboard.table.apiName': 'API Name',
    'dashboard.table.status': 'Status',
    'dashboard.table.calls': 'Calls (30d)',
    'dashboard.table.successRate': 'Success Rate',
    'dashboard.table.sharing': 'Sharing',
    'dashboard.table.actions': 'Actions',
    'dashboard.badge.imported': 'Imported API',
    'dashboard.badge.myApi': 'My API',
    'dashboard.originalAuthor': 'Original Author',
    'dashboard.status.active': 'Active',
    'dashboard.status.inactive': 'Inactive',
    'dashboard.status.error': 'Error',
    'dashboard.share.sharing': 'Sharing',
    'dashboard.share.share': 'Share',
    'dashboard.share.imported': 'Imported',
    'dashboard.menu.toggle': 'Toggle menu',
    'dashboard.menu.actions': 'Actions',
    'dashboard.menu.viewAnalytics': 'View Analytics',
    'dashboard.menu.keyManagement': 'Key Management',
    'dashboard.menu.settings': 'Settings',
    'dashboard.menu.apiKey': 'API Key',
    // User menu
    'user.menu.myAccount': 'My Account',
    'user.menu.settings': 'Settings',
    'user.menu.support': 'Support',
    'user.menu.logout': 'Logout',
    'user.menu.toggle': 'Toggle user menu',
    // Sample API data (for demo)
    'api.weather': 'Weather Data API',
    'api.stockMarket': 'Stock Market Feed',
    'api.locationService': 'User Location Service',
    'api.productCatalog': 'Product Catalog API',
    'api.paymentGateway': 'Payment Gateway Bridge',
    // Pricing page
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs and start building right away.',
    'pricing.free.title': 'Free',
    'pricing.free.description': 'Perfect for getting started with personal projects and learning.',
    'pricing.free.cta': 'Get Started Free',
    'pricing.pro.title': 'Pro',
    'pricing.pro.description': 'For professionals and teams who need powerful features.',
    'pricing.pro.cta': 'Start Pro Plan',
    'pricing.pro.popular': 'Most Popular',
    'pricing.pro.price': '$9.99',
    'pricing.pro.period': '/month',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API creation',
    'pricing.feature.apiCalls.free': '10,000 API calls per month',
    'pricing.feature.support.free': 'Community support',
    'pricing.feature.apiCreation.pro': 'Unlimited API creation',
    'pricing.feature.apiCalls.pro': '1,000,000 API calls per month',
    'pricing.feature.ai': 'AI+ features',
    'pricing.feature.support.pro': 'Priority email support',
    'pricing.feature.analytics': 'Advanced analytics',
    'pricing.footer': '© 2024 API Bridge. All rights reserved.',
    // Login page
    'login.title': 'API Bridge',
    'login.description': 'Enter your email below to sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.signIn': 'Sign In',
    'login.signInGoogle': 'Sign in with Google',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.emailPlaceholder': 'm@example.com',
  },
  ja: {
    'theme.light': 'ライト',
    'theme.dark': 'ダーク',
    'theme.toggle': 'テーマ切り替え',
    'language.toggle': '言語切り替え',
    'nav.features': '機能',
    'nav.pricing': '料金',
    'nav.docs': 'ドキュメント',
    'nav.signin': 'サインイン',
    'nav.getstarted': 'はじめる',
    'hero.title': '統合された',
    'hero.subtitle': 'APIを体験してください',
    'hero.description': '複数のパブリックAPIを単一の統合インターフェースで接続し、開発を簡素化します。より速く構築し、より簡単に統合できます。',
    'hero.cta': 'はじめる',
    'hero.learn': '詳細を見る',
    'features.title': '機能',
    'features.description': 'APIを効率的に接続・管理するために必要なすべて。',
    'feature.integration.title': 'API統合',
    'feature.integration.description': '複数のパブリックAPIを単一のインターフェースで統合します。',
    'feature.performance.title': '高速処理',
    'feature.performance.description': '最適化されたパフォーマンスで高速データ処理を提供します。',
    'feature.security.title': '安全な接続',
    'feature.security.description': 'セキュリティが強化された安全なAPI接続を保証します。',
    'footer.built': 'API Bridgeチームによって構築。ソースコードは',
    'footer.github': 'GitHub',
    'footer.available': 'で利用可能です。',
    'brand': 'APIブリッジ',
    // Dashboard navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.apiBoard': 'APIボード',
    'nav.suggestions': 'カスタムAPI作成',
    'nav.monitoring': 'モニタリング',
    'nav.settings': '設定',
    'nav.menu.toggle': 'ナビゲーションメニュー切り替え',
    // Dashboard stats
    'dashboard.stats.totalApis': '総API数',
    'dashboard.stats.activeKeys': 'アクティブキー',
    'dashboard.stats.totalCalls': '総呼び出し数（30日）',
    'dashboard.stats.uptime': '稼働時間',
    'dashboard.stats.lastMonth': '先月以降',
    'dashboard.stats.lastWeek': '先週以降',
    'dashboard.stats.vsLastMonth': '先月比',
    'dashboard.stats.allActiveApis': 'すべてのアクティブAPIで',
    // Dashboard API table
    'dashboard.myApis': 'マイAPI',
    'dashboard.myApis.description': 'カスタムデータソースAPIを管理します。',
    'dashboard.createApi': 'API作成',
    'dashboard.table.apiName': 'API名',
    'dashboard.table.status': 'ステータス',
    'dashboard.table.calls': '呼び出し数（30日）',
    'dashboard.table.successRate': '成功率',
    'dashboard.table.sharing': '共有',
    'dashboard.table.actions': 'アクション',
    'dashboard.badge.imported': 'インポートAPI',
    'dashboard.badge.myApi': 'マイAPI',
    'dashboard.originalAuthor': '元の作成者',
    'dashboard.status.active': 'アクティブ',
    'dashboard.status.inactive': '非アクティブ',
    'dashboard.status.error': 'エラー',
    'dashboard.share.sharing': '共有中',
    'dashboard.share.share': '共有',
    'dashboard.share.imported': 'インポート済み',
    'dashboard.menu.toggle': 'メニュー切り替え',
    'dashboard.menu.actions': 'アクション',
    'dashboard.menu.viewAnalytics': '分析を表示',
    'dashboard.menu.keyManagement': 'キー管理',
    'dashboard.menu.settings': '設定',
    'dashboard.menu.apiKey': 'APIキー',
    // User menu
    'user.menu.myAccount': 'マイアカウント',
    'user.menu.settings': '設定',
    'user.menu.support': 'サポート',
    'user.menu.logout': 'ログアウト',
    'user.menu.toggle': 'ユーザーメニュー切り替え',
    // Sample API data (for demo)
    'api.weather': '天気データAPI',
    'api.stockMarket': '株式市場フィード',
    'api.locationService': 'ユーザー位置情報サービス',
    'api.productCatalog': '製品カタログAPI',
    'api.paymentGateway': '決済ゲートウェイブリッジ',
    // Pricing page
    'pricing.title': 'シンプルで透明な料金',
    'pricing.subtitle': 'あなたのニーズに合ったプランを選択し、今すぐ構築を開始しましょう。',
    'pricing.free.title': '無料',
    'pricing.free.description': '個人プロジェクトや学習を始めるのに最適です。',
    'pricing.free.cta': '無料で始める',
    'pricing.pro.title': 'プロ',
    'pricing.pro.description': '強力な機能が必要な専門家やチームのためのプランです。',
    'pricing.pro.cta': 'プロプランを開始',
    'pricing.pro.popular': '最も人気',
    'pricing.pro.price': '¥1,290',
    'pricing.pro.period': '/月',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 API作成',
    'pricing.feature.apiCalls.free': '月10,000回のAPI呼び出し',
    'pricing.feature.support.free': 'コミュニティサポート',
    'pricing.feature.apiCreation.pro': '無制限API作成',
    'pricing.feature.apiCalls.pro': '月1,000,000回のAPI呼び出し',
    'pricing.feature.ai': 'AI+機能',
    'pricing.feature.support.pro': '優先メールサポート',
    'pricing.feature.analytics': '高度な分析機能',
    'pricing.footer': '© 2024 APIブリッジ。すべての権利を保有。',
    // Login page
    'login.title': 'APIブリッジ',
    'login.description': 'アカウントにサインインするには、下記にメールアドレスを入力してください',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.forgotPassword': 'パスワードをお忘れですか？',
    'login.signIn': 'サインイン',
    'login.signInGoogle': 'Googleでサインイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.signUp': 'サインアップ',
    'login.emailPlaceholder': 'm@example.com',
  },
  zh: {
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.toggle': '切换主题',
    'language.toggle': '切换语言',
    'nav.features': '功能',
    'nav.pricing': '价格',
    'nav.docs': '文档',
    'nav.signin': '登录',
    'nav.getstarted': '开始',
    'hero.title': '体验统一的',
    'hero.subtitle': 'API集成',
    'hero.description': '通过单一统一接口连接多个公共API，简化您的开发。更快构建，更轻松集成。',
    'hero.cta': '开始',
    'hero.learn': '了解更多',
    'features.title': '功能',
    'features.description': '高效连接和管理API所需的一切。',
    'feature.integration.title': 'API集成',
    'feature.integration.description': '通过单一接口集成多个公共API。',
    'feature.performance.title': '快速处理',
    'feature.performance.description': '提供优化性能的快速数据处理。',
    'feature.security.title': '安全连接',
    'feature.security.description': '确保增强安全性的安全API连接。',
    'footer.built': '由API Bridge团队构建。源代码可在',
    'footer.github': 'GitHub',
    'footer.available': '上获得。',
    'brand': 'API桥接',
    // Dashboard navigation
    'nav.dashboard': '仪表板',
    'nav.apiBoard': 'API面板',
    'nav.suggestions': '自定义API创建',
    'nav.monitoring': '监控',
    'nav.settings': '设置',
    'nav.menu.toggle': '切换导航菜单',
    // Dashboard stats
    'dashboard.stats.totalApis': '总API数',
    'dashboard.stats.activeKeys': '活跃密钥',
    'dashboard.stats.totalCalls': '总调用数（30天）',
    'dashboard.stats.uptime': '正常运行时间',
    'dashboard.stats.lastMonth': '自上月以来',
    'dashboard.stats.lastWeek': '自上周以来',
    'dashboard.stats.vsLastMonth': '与上月相比',
    'dashboard.stats.allActiveApis': '在所有活跃API中',
    // Dashboard API table
    'dashboard.myApis': '我的API',
    'dashboard.myApis.description': '管理您的自定义数据源API。',
    'dashboard.createApi': '创建API',
    'dashboard.table.apiName': 'API名称',
    'dashboard.table.status': '状态',
    'dashboard.table.calls': '调用数（30天）',
    'dashboard.table.successRate': '成功率',
    'dashboard.table.sharing': '共享',
    'dashboard.table.actions': '操作',
    'dashboard.badge.imported': '导入的API',
    'dashboard.badge.myApi': '我的API',
    'dashboard.originalAuthor': '原作者',
    'dashboard.status.active': '活跃',
    'dashboard.status.inactive': '非活跃',
    'dashboard.status.error': '错误',
    'dashboard.share.sharing': '共享中',
    'dashboard.share.share': '共享',
    'dashboard.share.imported': '已导入',
    'dashboard.menu.toggle': '切换菜单',
    'dashboard.menu.actions': '操作',
    'dashboard.menu.viewAnalytics': '查看分析',
    'dashboard.menu.keyManagement': '密钥管理',
    'dashboard.menu.settings': '设置',
    'dashboard.menu.apiKey': 'API密钥',
    // User menu
    'user.menu.myAccount': '我的账户',
    'user.menu.settings': '设置',
    'user.menu.support': '支持',
    'user.menu.logout': '退出登录',
    'user.menu.toggle': '切换用户菜单',
    // Sample API data (for demo)
    'api.weather': '天气数据API',
    'api.stockMarket': '股票市场订阅',
    'api.locationService': '用户位置服务',
    'api.productCatalog': '产品目录API',
    'api.paymentGateway': '支付网关桥接',
    // Pricing page
    'pricing.title': '简单透明的价格',
    'pricing.subtitle': '选择适合您需求的计划，立即开始构建。',
    'pricing.free.title': '免费',
    'pricing.free.description': '非常适合个人项目和学习入门。',
    'pricing.free.cta': '免费开始',
    'pricing.pro.title': '专业版',
    'pricing.pro.description': '为需要强大功能的专业人士和团队设计。',
    'pricing.pro.cta': '开始专业版计划',
    'pricing.pro.popular': '最受欢迎',
    'pricing.pro.price': '¥68',
    'pricing.pro.period': '/月',
    // Pricing features
    'pricing.feature.apiCreation.free': '1个API创建',
    'pricing.feature.apiCalls.free': '每月10,000次API调用',
    'pricing.feature.support.free': '社区支持',
    'pricing.feature.apiCreation.pro': '无限制API创建',
    'pricing.feature.apiCalls.pro': '每月1,000,000次API调用',
    'pricing.feature.ai': 'AI+功能',
    'pricing.feature.support.pro': '优先邮件支持',
    'pricing.feature.analytics': '高级分析功能',
    'pricing.footer': '© 2024 API桥接。保留所有权利。',
    // Login page
    'login.title': 'API桥接',
    'login.description': '请在下方输入您的邮箱以登录您的账户',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.forgotPassword': '忘记密码？',
    'login.signIn': '登录',
    'login.signInGoogle': '使用Google登录',
    'login.noAccount': '没有账户？',
    'login.signUp': '注册',
    'login.emailPlaceholder': 'm@example.com',
  },
  ru: {
    'theme.light': 'Светлая',
    'theme.dark': 'Тёмная',
    'theme.toggle': 'Переключить тему',
    'language.toggle': 'Переключить язык',
    'nav.features': 'Функции',
    'nav.pricing': 'Цены',
    'nav.docs': 'Документация',
    'nav.signin': 'Войти',
    'nav.getstarted': 'Начать',
    'hero.title': 'Испытайте единое',
    'hero.subtitle': 'API-интеграцию',
    'hero.description': 'Упростите разработку, подключив несколько публичных API через единый унифицированный интерфейс. Создавайте быстрее, интегрируйте проще.',
    'hero.cta': 'Начать',
    'hero.learn': 'Узнать больше',
    'features.title': 'Функции',
    'features.description': 'Всё необходимое для эффективного подключения и управления API.',
    'feature.integration.title': 'API-интеграция',
    'feature.integration.description': 'Интегрируйте несколько публичных API через единый интерфейс.',
    'feature.performance.title': 'Быстрая обработка',
    'feature.performance.description': 'Обеспечивает быструю обработку данных с оптимизированной производительностью.',
    'feature.security.title': 'Безопасное соединение',
    'feature.security.description': 'Гарантирует безопасные API-соединения с усиленной защитой.',
    'footer.built': 'Создано командой API Bridge. Исходный код доступен на',
    'footer.github': 'GitHub',
    'footer.available': '.',
    'brand': 'API Мост',
    // Dashboard navigation
    'nav.dashboard': 'Панель управления',
    'nav.apiBoard': 'API-панель',
    'nav.suggestions': 'Создание пользовательских API',
    'nav.monitoring': 'Мониторинг',
    'nav.settings': 'Настройки',
    'nav.menu.toggle': 'Переключить навигационное меню',
    // Dashboard stats
    'dashboard.stats.totalApis': 'Всего API',
    'dashboard.stats.activeKeys': 'Активные ключи',
    'dashboard.stats.totalCalls': 'Всего вызовов (30 дней)',
    'dashboard.stats.uptime': 'Время работы',
    'dashboard.stats.lastMonth': 'с прошлого месяца',
    'dashboard.stats.lastWeek': 'с прошлой недели',
    'dashboard.stats.vsLastMonth': 'по сравнению с прошлым месяцем',
    'dashboard.stats.allActiveApis': 'по всем активным API',
    // Dashboard API table
    'dashboard.myApis': 'Мои API',
    'dashboard.myApis.description': 'Управляйте вашими пользовательскими API источников данных.',
    'dashboard.createApi': 'Создать API',
    'dashboard.table.apiName': 'Название API',
    'dashboard.table.status': 'Статус',
    'dashboard.table.calls': 'Вызовы (30 дней)',
    'dashboard.table.successRate': 'Успешность',
    'dashboard.table.sharing': 'Общий доступ',
    'dashboard.table.actions': 'Действия',
    'dashboard.badge.imported': 'Импортированный API',
    'dashboard.badge.myApi': 'Мой API',
    'dashboard.originalAuthor': 'Первоначальный автор',
    'dashboard.status.active': 'Активен',
    'dashboard.status.inactive': 'Неактивен',
    'dashboard.status.error': 'Ошибка',
    'dashboard.share.sharing': 'Общий доступ',
    'dashboard.share.share': 'Поделиться',
    'dashboard.share.imported': 'Импортирован',
    'dashboard.menu.toggle': 'Переключить меню',
    'dashboard.menu.actions': 'Действия',
    'dashboard.menu.viewAnalytics': 'Просмотр аналитики',
    'dashboard.menu.keyManagement': 'Управление ключами',
    'dashboard.menu.settings': 'Настройки',
    'dashboard.menu.apiKey': 'API-ключ',
    // User menu
    'user.menu.myAccount': 'Мой аккаунт',
    'user.menu.settings': 'Настройки',
    'user.menu.support': 'Поддержка',
    'user.menu.logout': 'Выйти',
    'user.menu.toggle': 'Переключить пользовательское меню',
    // Sample API data (for demo)
    'api.weather': 'API данных о погоде',
    'api.stockMarket': 'Лента фондового рынка',
    'api.locationService': 'Сервис геолокации пользователя',
    'api.productCatalog': 'API каталога продуктов',
    'api.paymentGateway': 'Мост платёжного шлюза',
    // Pricing page
    'pricing.title': 'Простые и прозрачные цены',
    'pricing.subtitle': 'Выберите план, который подходит вашим потребностям, и начните создавать прямо сейчас.',
    'pricing.free.title': 'Бесплатно',
    'pricing.free.description': 'Идеально подходит для начала работы с личными проектами и обучения.',
    'pricing.free.cta': 'Начать бесплатно',
    'pricing.pro.title': 'Профессиональный',
    'pricing.pro.description': 'Для профессионалов и команд, которым нужны мощные функции.',
    'pricing.pro.cta': 'Начать профессиональный план',
    'pricing.pro.popular': 'Самый популярный',
    'pricing.pro.price': '990 ₽',
    'pricing.pro.period': '/мес',
    // Pricing features
    'pricing.feature.apiCreation.free': '1 создание API',
    'pricing.feature.apiCalls.free': '10 000 API-вызовов в месяц',
    'pricing.feature.support.free': 'Поддержка сообщества',
    'pricing.feature.apiCreation.pro': 'Неограниченное создание API',
    'pricing.feature.apiCalls.pro': '1 000 000 API-вызовов в месяц',
    'pricing.feature.ai': 'AI+ функции',
    'pricing.feature.support.pro': 'Приоритетная поддержка по email',
    'pricing.feature.analytics': 'Расширенная аналитика',
    'pricing.footer': '© 2024 API Мост. Все права защищены.',
    // Login page
    'login.title': 'API Мост',
    'login.description': 'Введите ваш email ниже, чтобы войти в ваш аккаунт',
    'login.email': 'Email',
    'login.password': 'Пароль',
    'login.forgotPassword': 'Забыли пароль?',
    'login.signIn': 'Войти',
    'login.signInGoogle': 'Войти через Google',
    'login.noAccount': 'Нет аккаунта?',
    'login.signUp': 'Зарегистрироваться',
    'login.emailPlaceholder': 'm@example.com',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ko');

  // Load language from sessionStorage on initial load
  useEffect(() => {
    const savedLanguage = sessionStorage.getItem('language') as Language;
    if (savedLanguage && ['ko', 'en', 'ja', 'zh', 'ru'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to sessionStorage whenever it changes
  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    sessionStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Helper function to translate dynamic content with fallback
  const translateIfExists = (key: string, fallback: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, translateIfExists }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};